"""Registry layer — gas / unit / statistic enums and alias registries.

``codes.json`` is the source of truth; typed enums are generated by
``scripts/gen_codes.py`` into ``_codes_gen.py``. See ``docs/design.md`` §5.3.
"""
