"""Registry layer — gas / unit / statistic enums and alias registries.

``codes.json`` is the source of truth; typed enums are generated by
``scripts/gen_codes.py`` into ``_codes_gen.py``. See ``docs/design.md`` §5.3.
"""

from __future__ import annotations

from alicatlib.registry.aliases import AliasRegistry, UnitRegistry
from alicatlib.registry.gases import Gas, gas_registry
from alicatlib.registry.loop_control import (
    LOOP_CONTROL_VARIABLE_CODES,
    LoopControlVariable,
    coerce_loop_control_variable,
)
from alicatlib.registry.statistics import Statistic, statistic_registry
from alicatlib.registry.units import Unit, UnitCategory, unit_registry

__all__ = [
    "LOOP_CONTROL_VARIABLE_CODES",
    "AliasRegistry",
    "Gas",
    "LoopControlVariable",
    "Statistic",
    "Unit",
    "UnitCategory",
    "UnitRegistry",
    "coerce_loop_control_variable",
    "gas_registry",
    "statistic_registry",
    "unit_registry",
]
