"""GENERATED FILE — do not edit by hand.

Regenerated by ``scripts/gen_codes.py`` from
``src/alicatlib/registry/data/codes.json``. CI enforces that this file matches
the committed ``codes.json``.

Public types are re-exported from :mod:`alicatlib.registry`; downstream code
should import from there, not from this module directly.
"""

from __future__ import annotations

from enum import StrEnum
from typing import Final, Mapping


class UnitCategory(StrEnum):
    """Unit category, per Primer Appendix B sections."""

    STD_NORM_FLOW = "std_norm_flow"
    TRUE_MASS_FLOW = "true_mass_flow"
    TOTAL_STD_NORM_VOLUME = "total_std_norm_volume"
    VOLUMETRIC_FLOW = "volumetric_flow"
    TOTAL_VOLUME = "total_volume"
    PRESSURE = "pressure"
    TEMPERATURE = "temperature"
    TIME_INTERVAL = "time_interval"

    @property
    def display_name(self) -> str:
        """Human-readable name for this category."""
        return UNIT_CATEGORY_DISPLAY_NAMES[self]


class Statistic(StrEnum):
    """Device statistic code (Primer Appendix A)."""

    NONE = 'none'
    ABS_PRESS = 'abs_press'
    TEMP_STREAM = 'temp_stream'
    VOL_FLOW = 'vol_flow'
    MASS_FLOW = 'mass_flow'
    GAUGE_PRESS = 'gauge_press'
    DIFF_PRESS = 'diff_press'
    TOT_VOL = 'tot_vol'
    TOT_MASS = 'tot_mass'
    TOTALIZING_TIME = 'totalizing_time'
    BATCH_VOL_REMAIN = 'batch_vol_remain'
    BATCH_MASS_REMAIN = 'batch_mass_remain'
    VALVE_DRIVE = 'valve_drive'
    TIME_MEAS_REMAIN = 'time_meas_remain'
    BARO_PRESS = 'baro_press'
    TEMP_EXT = 'temp_ext'
    VOL_FLOW_EXT = 'vol_flow_ext'
    TOT_VOL_EXT = 'tot_vol_ext'
    BATCH_VOL_EXT_REMAIN = 'batch_vol_ext_remain'
    TEMP_EXT_VFR = 'temp_ext_vfr'
    TEMP_EXT_VFR_SRC = 'temp_ext_vfr_src'
    REL_HUM = 'rel_hum'
    STATUS = 'status'
    SETPT = 'setpt'
    ABS_PRESS_SETPT = 'abs_press_setpt'
    VOL_FLOW_SETPT = 'vol_flow_setpt'
    MASS_FLOW_SETPT = 'mass_flow_setpt'
    GAUGE_PRESS_SETPT = 'gauge_press_setpt'
    DIFF_PRESS_SETPT = 'diff_press_setpt'
    VALVE_DRIVE_SETPT = 'valve_drive_setpt'
    VOL_FLOW_EXT_SETPT = 'vol_flow_ext_setpt'
    ABS_PRESS_AVG = 'abs_press_avg'
    TEMP_STREAM_AVG = 'temp_stream_avg'
    VOL_FLOW_AVG = 'vol_flow_avg'
    MASS_FLOW_AVG = 'mass_flow_avg'
    GAUGE_PRESS_AVG = 'gauge_press_avg'
    BARO_PRESS_AVG = 'baro_press_avg'
    VOL_FLOW_EXT_AVG = 'vol_flow_ext_avg'
    TEMP_EXT_VFR_AVG = 'temp_ext_vfr_avg'
    TEMP_EXT_VFR_SRC_AVG = 'temp_ext_vfr_src_avg'
    REL_HUM_AVG = 'rel_hum_avg'
    ABS_PRESS_PEAK = 'abs_press_peak'
    VOL_FLOW_PEAK = 'vol_flow_peak'
    MASS_FLOW_PEAK = 'mass_flow_peak'
    GAUGE_PRESS_PEAK = 'gauge_press_peak'
    BARO_PRESS_PEAK = 'baro_press_peak'
    VOL_FLOW_EXT_PEAK = 'vol_flow_ext_peak'
    TEMP_EXT_VFR_PEAK = 'temp_ext_vfr_peak'
    REL_HUM_PEAK = 'rel_hum_peak'
    SETPT_ERR = 'setpt_err'
    ABS_PRESS_SETPT_ERR = 'abs_press_setpt_err'
    ABS_PRESS_MIN = 'abs_press_min'
    ABS_PRESS_MAX = 'abs_press_max'
    TEMP_STREAM_MIN = 'temp_stream_min'
    TEMP_STREAM_MAX = 'temp_stream_max'
    VOL_FLOW_SETPT_ERR = 'vol_flow_setpt_err'
    VOL_FLOW_MIN = 'vol_flow_min'
    VOL_FLOW_MAX = 'vol_flow_max'
    MASS_FLOW_SETPT_ERR = 'mass_flow_setpt_err'
    MASS_FLOW_MIN = 'mass_flow_min'
    MASS_FLOW_MAX = 'mass_flow_max'
    GAUGE_PRESS_SETPT_ERR = 'gauge_press_setpt_err'
    GAUGE_PRESS_MIN = 'gauge_press_min'
    GAUGE_PRESS_MAX = 'gauge_press_max'
    DIFF_PRESS_SETPT_ERR = 'diff_press_setpt_err'
    DIFF_PRESS_MIN = 'diff_press_min'
    DIFF_PRESS_MAX = 'diff_press_max'
    BARO_PRESS_MIN = 'baro_press_min'
    BARO_PRESS_MAX = 'baro_press_max'
    TEMP_EXT_MIN = 'temp_ext_min'
    TEMP_EXT_MAX = 'temp_ext_max'
    VOL_FLOW_EXT_SETPT_ERR = 'vol_flow_ext_setpt_err'
    VOL_FLOW_EXT_MIN = 'vol_flow_ext_min'
    VOL_FLOW_EXT_MAX = 'vol_flow_ext_max'
    TEMP_EXT_VFR_MIN = 'temp_ext_vfr_min'
    TEMP_EXT_VFR_MAX = 'temp_ext_vfr_max'
    REL_HUM_MIN = 'rel_hum_min'
    REL_HUM_MAX = 'rel_hum_max'
    ABS_PRESS_SECOND = 'abs_press_second'
    ABS_PRESS_SECOND_SETPT = 'abs_press_second_setpt'
    ABS_PRESS_SECOND_SETPT_ERR = 'abs_press_second_setpt_err'
    ABS_PRESS_SECOND_MIN = 'abs_press_second_min'
    ABS_PRESS_SECOND_MAX = 'abs_press_second_max'
    GAUGE_PRESS_SECOND = 'gauge_press_second'
    GAUGE_PRESS_SECOND_SETPT = 'gauge_press_second_setpt'
    GAUGE_PRESS_SECOND_SETPT_ERR = 'gauge_press_second_setpt_err'
    GAUGE_PRESS_SECOND_MIN = 'gauge_press_second_min'
    GAUGE_PRESS_SECOND_MAX = 'gauge_press_second_max'
    DIFF_PRESS_SECOND = 'diff_press_second'
    DIFF_PRESS_SECOND_SETPT = 'diff_press_second_setpt'
    DIFF_PRESS_SECOND_SETPT_ERR = 'diff_press_second_setpt_err'
    DIFF_PRESS_SECOND_MIN = 'diff_press_second_min'
    DIFF_PRESS_SECOND_MAX = 'diff_press_second_max'
    USER_TIME = 'user_time'
    USER_DATE = 'user_date'
    FLUID_NAME = 'fluid_name'
    MEAS_ID = 'meas_id'
    MEAS_STAT = 'meas_stat'

    @property
    def code(self) -> int:
        """Numeric Alicat code (see Appendix A/B/C)."""
        return STATISTIC_CODES[self]

    @property
    def display_name(self) -> str:
        """Human-readable name from the primer."""
        return STATISTIC_DISPLAY_NAMES[self]


class Gas(StrEnum):
    """Gas / gas mixture (Primer Appendix C)."""

    AIR = 'Air'
    AR = 'Ar'
    CH4 = 'CH4'
    CO = 'CO'
    CO2 = 'CO2'
    C2H6 = 'C2H6'
    H2 = 'H2'
    HE = 'He'
    N2 = 'N2'
    N2O = 'N2O'
    NE = 'Ne'
    O2 = 'O2'
    C3H8 = 'C3H8'
    NC4H10 = 'nC4H10'
    C2H2 = 'C2H2'
    C2H4 = 'C2H4'
    IC4H10 = 'iC4H10'
    KR = 'Kr'
    XE = 'Xe'
    SF6 = 'SF6'
    C_25 = 'C-25'
    C_10 = 'C-10'
    C_8 = 'C-8'
    C_2 = 'C-2'
    C_75 = 'C-75'
    HE_25 = 'He-25'
    HE_75 = 'He-75'
    A1025 = 'A1025'
    STAR29 = 'Star29'
    P_5 = 'P-5'
    NO = 'NO'
    NF3 = 'NF3'
    NH3 = 'NH3'
    CL2 = 'Cl2'
    H2S = 'H2S'
    SO2 = 'SO2'
    C3H6 = 'C3H6'
    BUTEN_1 = '1Buten'
    CBUTEN = 'cButen'
    IBUTEN = 'iButen'
    TBUTEN = 'tButen'
    COS = 'COS'
    DME = 'DME'
    SIH4 = 'SiH4'
    R_11 = 'R-11'
    R_115 = 'R-115'
    R_116 = 'R-116'
    R_124 = 'R-124'
    R_125 = 'R-125'
    R_134A = 'R-134A'
    R_14 = 'R-14'
    R_142B = 'R-142b'
    R_143A = 'R-143a'
    R_152A = 'R-152a'
    R_22 = 'R-22'
    R_23 = 'R-23'
    R_32 = 'R-32'
    R_318 = 'R-318'
    R_404A = 'R-404A'
    R_407C = 'R-407C'
    R_410A = 'R-410A'
    R_507A = 'R-507A'
    C_15 = 'C-15'
    C_20 = 'C-20'
    C_50 = 'C-50'
    HE_50 = 'He-50'
    HE_90 = 'He-90'
    BIO5M = 'Bio5M'
    BIO10M = 'Bio10M'
    BIO15M = 'Bio15M'
    BIO20M = 'Bio20M'
    BIO25M = 'Bio25M'
    BIO30M = 'Bio30M'
    BIO35M = 'Bio35M'
    BIO40M = 'Bio40M'
    BIO45M = 'Bio45M'
    BIO50M = 'Bio50M'
    BIO55M = 'Bio55M'
    BIO60M = 'Bio60M'
    BIO65M = 'Bio65M'
    BIO70M = 'Bio70M'
    BIO75M = 'Bio75M'
    BIO80M = 'Bio80M'
    BIO85M = 'Bio85M'
    BIO90M = 'Bio90M'
    BIO95M = 'Bio95M'
    EAN_32 = 'EAN-32'
    EAN_36 = 'EAN-36'
    EAN_40 = 'EAN-40'
    HEOX20 = 'HeOx20'
    HEOX21 = 'HeOx21'
    HEOX30 = 'HeOx30'
    HEOX40 = 'HeOx40'
    HEOX50 = 'HeOx50'
    HEOX60 = 'HeOx60'
    HEOX80 = 'HeOx80'
    HEOX99 = 'HeOx99'
    EA_40 = 'EA-40'
    EA_60 = 'EA-60'
    EA_80 = 'EA-80'
    METAB = 'Metab'
    LG_4_5 = 'LG-4.5'
    LG_6 = 'LG-6'
    LG_7 = 'LG-7'
    LG_9 = 'LG-9'
    HENE_9 = 'HeNe-9'
    LG_9_4 = 'LG-9.4'
    SYNG_1 = 'SynG-1'
    SYNG_2 = 'SynG-2'
    SYNG_3 = 'SynG-3'
    SYNG_4 = 'SynG-4'
    NATG_1 = 'NatG-1'
    NATG_2 = 'NatG-2'
    NATG_3 = 'NatG-3'
    COALG = 'CoalG'
    ENDO = 'Endo'
    HHO = 'HHO'
    HD_5 = 'HD-5'
    HD_10 = 'HD-10'
    OCG_89 = 'OCG-89'
    OCG_93 = 'OCG-93'
    OCG_95 = 'OCG-95'
    FG_1 = 'FG-1'
    FG_2 = 'FG-2'
    FG_3 = 'FG-3'
    FG_4 = 'FG-4'
    FG_5 = 'FG-5'
    FG_6 = 'FG-6'
    P_10 = 'P-10'
    D_2 = 'D-2'
    MIX_236 = 'Mix236'
    MIX_237 = 'Mix237'
    MIX_238 = 'Mix238'
    MIX_239 = 'Mix239'
    MIX_240 = 'Mix240'
    MIX_241 = 'Mix241'
    MIX_242 = 'Mix242'
    MIX_243 = 'Mix243'
    MIX_244 = 'Mix244'
    MIX_245 = 'Mix245'
    MIX_246 = 'Mix246'
    MIX_247 = 'Mix247'
    MIX_248 = 'Mix248'
    MIX_249 = 'Mix249'
    MIX_250 = 'Mix250'
    MIX_251 = 'Mix251'
    MIX_252 = 'Mix252'
    MIX_253 = 'Mix253'
    MIX_254 = 'Mix254'
    MIX_255 = 'Mix255'

    @property
    def code(self) -> int:
        """Numeric Alicat code (see Appendix A/B/C)."""
        return GAS_CODES[self]

    @property
    def display_name(self) -> str:
        """Human-readable name from the primer."""
        return GAS_DISPLAY_NAMES[self]


class Unit(StrEnum):
    """Engineering unit (Primer Appendix B)."""

    DEFAULT = 'default'
    UNKNOWN = 'unknown'
    COUNT = 'count'
    PERCENT = '%'
    SUL_M = 'SμL/m'
    SML_S = 'SmL/s'
    SML_M = 'SmL/m'
    SML_H = 'SmL/h'
    SL_S = 'SL/s'
    SLPM = 'SLPM'
    SL_H = 'SL/h'
    SCCS = 'SCCS'
    SCCM = 'SCCM'
    SCM3_H = 'Scm³/h'
    SM3_M = 'Sm³/m'
    SM3_H = 'Sm³/h'
    SM3_D = 'Sm³/d'
    SIN3_M = 'Sin³/m'
    SCFM = 'SCFM'
    SCFH = 'SCFH'
    KSCFM = 'kSCFM'
    SCFD = 'SCFD'
    NUL_M = 'NμL/m'
    NML_S = 'NmL/s'
    NML_M = 'NmL/m'
    NML_H = 'NmL/h'
    NL_S = 'NL/s'
    NLPM = 'NLPM'
    NL_H = 'NL/h'
    NCCS = 'NCCS'
    NCCM = 'NCCM'
    NCM3_H = 'Ncm³/h'
    NM3_M = 'Nm³/m'
    NM3_H = 'Nm³/h'
    NM3_D = 'Nm³/d'
    MG_S = 'mg/s'
    MG_M = 'mg/m'
    G_S = 'g/s'
    G_M = 'g/m'
    G_H = 'g/h'
    KG_M = 'kg/m'
    KG_H = 'kg/h'
    OZ_S = 'oz/s'
    OZ_M = 'oz/m'
    LB_M = 'lb/m'
    LB_H = 'lb/h'
    SUL = 'SμL'
    SML = 'SmL'
    SL = 'SL'
    SCM3 = 'Scm³'
    SM3 = 'Sm³'
    SIN3 = 'Sin³'
    SFT3 = 'Sft³'
    KSFT3 = 'kSft³'
    NUL = 'NμL'
    NML = 'NmL'
    NL = 'NL'
    NCM3 = 'Ncm³'
    NM3 = 'Nm³'
    UL_M = 'μL/m'
    ML_S = 'mL/s'
    ML_M = 'mL/m'
    ML_H = 'mL/h'
    L_S = 'L/s'
    LPM = 'LPM'
    L_H = 'L/h'
    US_GPM = 'US GPM'
    US_GPH = 'US GPH'
    CCS = 'CCS'
    CCM = 'CCM'
    CM3_H = 'cm³/h'
    M3_M = 'm³/m'
    M3_H = 'm³/h'
    M3_D = 'm³/d'
    IN3_M = 'in³/m'
    CFM = 'CFM'
    CFH = 'CFH'
    CFD = 'CFD'
    UL = 'μL'
    ML = 'mL'
    L = 'L'
    US_GAL = 'US GAL'
    CM3 = 'cm³'
    M3 = 'm³'
    IN3 = 'in³'
    FT3 = 'ft³'
    UP = 'μP'
    PA = 'Pa'
    HPA = 'hPa'
    KPA = 'kPa'
    MPA = 'MPa'
    MBAR = 'mbar'
    BAR = 'bar'
    G_CM2 = 'g/cm²'
    KG_CM2 = 'kg/cm²'
    PSI = 'PSI'
    PSF = 'PSF'
    MTORR = 'mTorr'
    TORR = 'torr'
    MMHG = 'mmHg'
    INHG = 'inHg'
    MMH2O = 'mmH2O'
    MMH2O_60F = 'mmH2O@60F'
    CMH2O = 'cmH2O'
    CMH2O_60F = 'cmH2O@60F'
    INH2O = 'inH2O'
    INH2O_60F = 'inH2O@60F'
    ATM = 'atm'
    V = 'V'
    DEG_C = '°C'
    DEG_F = '°F'
    DEG_K = '°K'
    DEG_RA = '°Ra'
    H_M_S = 'h:m:s'
    MS = 'ms'
    S = 's'
    M = 'm'
    HOUR = 'hour'
    DAY = 'day'

    @property
    def code(self) -> int:
        """Numeric Alicat code (see Appendix A/B/C)."""
        return UNIT_CODES[self]

    @property
    def display_name(self) -> str:
        """Human-readable name from the primer."""
        return UNIT_DISPLAY_NAMES[self]

    @property
    def categories(self) -> frozenset[UnitCategory]:
        """Primer Appendix B categories this unit belongs to."""
        return UNIT_CATEGORIES[self]


UNIT_CATEGORY_DISPLAY_NAMES: Final[Mapping[UnitCategory, str]] = {
    UnitCategory.STD_NORM_FLOW: 'Standard and Normal Flow (Primer Appendix B-1)',
    UnitCategory.TRUE_MASS_FLOW: 'True Mass Flow (Primer Appendix B-2)',
    UnitCategory.TOTAL_STD_NORM_VOLUME: 'Total Standard and Normal Volume (Primer Appendix B-3)',
    UnitCategory.VOLUMETRIC_FLOW: 'Volumetric Flow (Primer Appendix B-4)',
    UnitCategory.TOTAL_VOLUME: 'Total Volume (Primer Appendix B-5)',
    UnitCategory.PRESSURE: 'Pressure (Primer Appendix B-6)',
    UnitCategory.TEMPERATURE: 'Temperature (Primer Appendix B-7)',
    UnitCategory.TIME_INTERVAL: 'Time Interval (Primer Appendix B-8)',
}


STATISTIC_CODES: Final[Mapping[Statistic, int]] = {
    Statistic.NONE: 1,
    Statistic.ABS_PRESS: 2,
    Statistic.TEMP_STREAM: 3,
    Statistic.VOL_FLOW: 4,
    Statistic.MASS_FLOW: 5,
    Statistic.GAUGE_PRESS: 6,
    Statistic.DIFF_PRESS: 7,
    Statistic.TOT_VOL: 8,
    Statistic.TOT_MASS: 9,
    Statistic.TOTALIZING_TIME: 10,
    Statistic.BATCH_VOL_REMAIN: 11,
    Statistic.BATCH_MASS_REMAIN: 12,
    Statistic.VALVE_DRIVE: 13,
    Statistic.TIME_MEAS_REMAIN: 14,
    Statistic.BARO_PRESS: 15,
    Statistic.TEMP_EXT: 16,
    Statistic.VOL_FLOW_EXT: 17,
    Statistic.TOT_VOL_EXT: 18,
    Statistic.BATCH_VOL_EXT_REMAIN: 19,
    Statistic.TEMP_EXT_VFR: 20,
    Statistic.TEMP_EXT_VFR_SRC: 21,
    Statistic.REL_HUM: 25,
    Statistic.STATUS: 26,
    Statistic.SETPT: 32,
    Statistic.ABS_PRESS_SETPT: 34,
    Statistic.VOL_FLOW_SETPT: 36,
    Statistic.MASS_FLOW_SETPT: 37,
    Statistic.GAUGE_PRESS_SETPT: 38,
    Statistic.DIFF_PRESS_SETPT: 39,
    Statistic.VALVE_DRIVE_SETPT: 45,
    Statistic.VOL_FLOW_EXT_SETPT: 49,
    Statistic.ABS_PRESS_AVG: 66,
    Statistic.TEMP_STREAM_AVG: 67,
    Statistic.VOL_FLOW_AVG: 68,
    Statistic.MASS_FLOW_AVG: 69,
    Statistic.GAUGE_PRESS_AVG: 70,
    Statistic.BARO_PRESS_AVG: 79,
    Statistic.VOL_FLOW_EXT_AVG: 81,
    Statistic.TEMP_EXT_VFR_AVG: 84,
    Statistic.TEMP_EXT_VFR_SRC_AVG: 85,
    Statistic.REL_HUM_AVG: 89,
    Statistic.ABS_PRESS_PEAK: 98,
    Statistic.VOL_FLOW_PEAK: 100,
    Statistic.MASS_FLOW_PEAK: 101,
    Statistic.GAUGE_PRESS_PEAK: 102,
    Statistic.BARO_PRESS_PEAK: 111,
    Statistic.VOL_FLOW_EXT_PEAK: 113,
    Statistic.TEMP_EXT_VFR_PEAK: 116,
    Statistic.REL_HUM_PEAK: 121,
    Statistic.SETPT_ERR: 133,
    Statistic.ABS_PRESS_SETPT_ERR: 149,
    Statistic.ABS_PRESS_MIN: 150,
    Statistic.ABS_PRESS_MAX: 151,
    Statistic.TEMP_STREAM_MIN: 158,
    Statistic.TEMP_STREAM_MAX: 159,
    Statistic.VOL_FLOW_SETPT_ERR: 165,
    Statistic.VOL_FLOW_MIN: 166,
    Statistic.VOL_FLOW_MAX: 167,
    Statistic.MASS_FLOW_SETPT_ERR: 173,
    Statistic.MASS_FLOW_MIN: 174,
    Statistic.MASS_FLOW_MAX: 175,
    Statistic.GAUGE_PRESS_SETPT_ERR: 181,
    Statistic.GAUGE_PRESS_MIN: 182,
    Statistic.GAUGE_PRESS_MAX: 183,
    Statistic.DIFF_PRESS_SETPT_ERR: 189,
    Statistic.DIFF_PRESS_MIN: 190,
    Statistic.DIFF_PRESS_MAX: 191,
    Statistic.BARO_PRESS_MIN: 254,
    Statistic.BARO_PRESS_MAX: 255,
    Statistic.TEMP_EXT_MIN: 262,
    Statistic.TEMP_EXT_MAX: 263,
    Statistic.VOL_FLOW_EXT_SETPT_ERR: 268,
    Statistic.VOL_FLOW_EXT_MIN: 270,
    Statistic.VOL_FLOW_EXT_MAX: 271,
    Statistic.TEMP_EXT_VFR_MIN: 294,
    Statistic.TEMP_EXT_VFR_MAX: 295,
    Statistic.REL_HUM_MIN: 334,
    Statistic.REL_HUM_MAX: 335,
    Statistic.ABS_PRESS_SECOND: 344,
    Statistic.ABS_PRESS_SECOND_SETPT: 345,
    Statistic.ABS_PRESS_SECOND_SETPT_ERR: 349,
    Statistic.ABS_PRESS_SECOND_MIN: 350,
    Statistic.ABS_PRESS_SECOND_MAX: 351,
    Statistic.GAUGE_PRESS_SECOND: 352,
    Statistic.GAUGE_PRESS_SECOND_SETPT: 353,
    Statistic.GAUGE_PRESS_SECOND_SETPT_ERR: 357,
    Statistic.GAUGE_PRESS_SECOND_MIN: 358,
    Statistic.GAUGE_PRESS_SECOND_MAX: 359,
    Statistic.DIFF_PRESS_SECOND: 360,
    Statistic.DIFF_PRESS_SECOND_SETPT: 361,
    Statistic.DIFF_PRESS_SECOND_SETPT_ERR: 365,
    Statistic.DIFF_PRESS_SECOND_MIN: 366,
    Statistic.DIFF_PRESS_SECOND_MAX: 367,
    Statistic.USER_TIME: 392,
    Statistic.USER_DATE: 400,
    Statistic.FLUID_NAME: 703,
    Statistic.MEAS_ID: 801,
    Statistic.MEAS_STAT: 802,
}


STATISTIC_DISPLAY_NAMES: Final[Mapping[Statistic, str]] = {
    Statistic.NONE: 'None',
    Statistic.ABS_PRESS: 'Pressure, absolute',
    Statistic.TEMP_STREAM: 'Temperature, stream',
    Statistic.VOL_FLOW: 'Volumetric flow',
    Statistic.MASS_FLOW: 'Mass flow',
    Statistic.GAUGE_PRESS: 'Pressure, gauge',
    Statistic.DIFF_PRESS: 'Pressure, differential',
    Statistic.TOT_VOL: 'Total volume',
    Statistic.TOT_MASS: 'Total mass',
    Statistic.TOTALIZING_TIME: 'Time, totalizing',
    Statistic.BATCH_VOL_REMAIN: 'Batch volume remaining',
    Statistic.BATCH_MASS_REMAIN: 'Batch mass remaining',
    Statistic.VALVE_DRIVE: 'Valve drive',
    Statistic.TIME_MEAS_REMAIN: 'Time, measurement remaining',
    Statistic.BARO_PRESS: 'Pressure, barometric',
    Statistic.TEMP_EXT: 'Temperature, external',
    Statistic.VOL_FLOW_EXT: 'Volumetric flow, external',
    Statistic.TOT_VOL_EXT: 'Total volume, external',
    Statistic.BATCH_VOL_EXT_REMAIN: 'Batch volume, external remaining',
    Statistic.TEMP_EXT_VFR: 'Temperature, external volumetric flow reference',
    Statistic.TEMP_EXT_VFR_SRC: 'Temperature, external volumetric flow reference source',
    Statistic.REL_HUM: 'Vapor saturation',
    Statistic.STATUS: 'Status',
    Statistic.SETPT: 'Setpoint',
    Statistic.ABS_PRESS_SETPT: 'Pressure, absolute setpoint',
    Statistic.VOL_FLOW_SETPT: 'Volumetric flow setpoint',
    Statistic.MASS_FLOW_SETPT: 'Mass flow setpoint',
    Statistic.GAUGE_PRESS_SETPT: 'Pressure, gauge setpoint',
    Statistic.DIFF_PRESS_SETPT: 'Pressure, differential setpoint',
    Statistic.VALVE_DRIVE_SETPT: 'Valve drive setpoint',
    Statistic.VOL_FLOW_EXT_SETPT: 'Volumetric flow, external setpoint',
    Statistic.ABS_PRESS_AVG: 'Pressure, absolute average',
    Statistic.TEMP_STREAM_AVG: 'Temperature, stream average',
    Statistic.VOL_FLOW_AVG: 'Volumetric flow, average',
    Statistic.MASS_FLOW_AVG: 'Mass flow, average',
    Statistic.GAUGE_PRESS_AVG: 'Pressure, gauge average',
    Statistic.BARO_PRESS_AVG: 'Pressure, barometric average',
    Statistic.VOL_FLOW_EXT_AVG: 'Volumetric flow, external average',
    Statistic.TEMP_EXT_VFR_AVG: 'Temperature, external volumetric flow reference average',
    Statistic.TEMP_EXT_VFR_SRC_AVG: 'Temperature, external volumetric flow reference source average',
    Statistic.REL_HUM_AVG: 'Vapor saturation, average',
    Statistic.ABS_PRESS_PEAK: 'Pressure, absolute peak',
    Statistic.VOL_FLOW_PEAK: 'Volumetric flow, peak',
    Statistic.MASS_FLOW_PEAK: 'Mass flow, peak',
    Statistic.GAUGE_PRESS_PEAK: 'Pressure, gauge peak',
    Statistic.BARO_PRESS_PEAK: 'Pressure, barometric peak',
    Statistic.VOL_FLOW_EXT_PEAK: 'Volumetric flow, external peak',
    Statistic.TEMP_EXT_VFR_PEAK: 'Temperature, external volumetric flow reference peak',
    Statistic.REL_HUM_PEAK: 'Vapor saturation, peak',
    Statistic.SETPT_ERR: 'Setpoint error',
    Statistic.ABS_PRESS_SETPT_ERR: 'Pressure, absolute setpoint error',
    Statistic.ABS_PRESS_MIN: 'Pressure, absolute minimum',
    Statistic.ABS_PRESS_MAX: 'Pressure, absolute maximum',
    Statistic.TEMP_STREAM_MIN: 'Temperature, stream minimum',
    Statistic.TEMP_STREAM_MAX: 'Temperature, stream maximum',
    Statistic.VOL_FLOW_SETPT_ERR: 'Volumetric flow setpoint error',
    Statistic.VOL_FLOW_MIN: 'Volumetric flow, minimum',
    Statistic.VOL_FLOW_MAX: 'Volumetric flow, maximum',
    Statistic.MASS_FLOW_SETPT_ERR: 'Mass flow setpoint error',
    Statistic.MASS_FLOW_MIN: 'Mass flow, minimum',
    Statistic.MASS_FLOW_MAX: 'Mass flow, maximum',
    Statistic.GAUGE_PRESS_SETPT_ERR: 'Pressure, gauge setpoint error',
    Statistic.GAUGE_PRESS_MIN: 'Pressure, gauge minimum',
    Statistic.GAUGE_PRESS_MAX: 'Pressure, gauge maximum',
    Statistic.DIFF_PRESS_SETPT_ERR: 'Pressure, differential setpoint error',
    Statistic.DIFF_PRESS_MIN: 'Pressure, differential minimum',
    Statistic.DIFF_PRESS_MAX: 'Pressure, differential maximum',
    Statistic.BARO_PRESS_MIN: 'Pressure, barometric minimum',
    Statistic.BARO_PRESS_MAX: 'Pressure, barometric maximum',
    Statistic.TEMP_EXT_MIN: 'Temperature, external minimum',
    Statistic.TEMP_EXT_MAX: 'Temperature, external maximum',
    Statistic.VOL_FLOW_EXT_SETPT_ERR: 'Volumetric flow external setpoint error',
    Statistic.VOL_FLOW_EXT_MIN: 'Volumetric flow, external minimum',
    Statistic.VOL_FLOW_EXT_MAX: 'Volumetric flow, external maximum',
    Statistic.TEMP_EXT_VFR_MIN: 'Temperature, external volumetric flow reference minimum',
    Statistic.TEMP_EXT_VFR_MAX: 'Temperature, external volumetric flow reference maximum',
    Statistic.REL_HUM_MIN: 'Vapor saturation, minimum',
    Statistic.REL_HUM_MAX: 'Vapor saturation, maximum',
    Statistic.ABS_PRESS_SECOND: 'Pressure, second absolute',
    Statistic.ABS_PRESS_SECOND_SETPT: 'Pressure, second absolute setpoint',
    Statistic.ABS_PRESS_SECOND_SETPT_ERR: 'Pressure, second absolute setpoint error',
    Statistic.ABS_PRESS_SECOND_MIN: 'Pressure, second absolute minimum',
    Statistic.ABS_PRESS_SECOND_MAX: 'Pressure, second absolute maximum',
    Statistic.GAUGE_PRESS_SECOND: 'Pressure, second gauge',
    Statistic.GAUGE_PRESS_SECOND_SETPT: 'Pressure, second gauge setpoint',
    Statistic.GAUGE_PRESS_SECOND_SETPT_ERR: 'Pressure, second gauge setpoint error',
    Statistic.GAUGE_PRESS_SECOND_MIN: 'Pressure, second gauge minimum',
    Statistic.GAUGE_PRESS_SECOND_MAX: 'Pressure, second gauge maximum',
    Statistic.DIFF_PRESS_SECOND: 'Pressure, second differential',
    Statistic.DIFF_PRESS_SECOND_SETPT: 'Pressure, second differential setpoint',
    Statistic.DIFF_PRESS_SECOND_SETPT_ERR: 'Pressure, second differential setpoint error',
    Statistic.DIFF_PRESS_SECOND_MIN: 'Pressure, second differential minimum',
    Statistic.DIFF_PRESS_SECOND_MAX: 'Pressure, second differential maximum',
    Statistic.USER_TIME: 'Time, user',
    Statistic.USER_DATE: 'Date, user',
    Statistic.FLUID_NAME: 'Fluid name',
    Statistic.MEAS_ID: 'Measurement id',
    Statistic.MEAS_STAT: 'Measurement status',
}


STATISTIC_BY_CODE: Final[Mapping[int, Statistic]] = {
    1: Statistic.NONE,
    2: Statistic.ABS_PRESS,
    3: Statistic.TEMP_STREAM,
    4: Statistic.VOL_FLOW,
    5: Statistic.MASS_FLOW,
    6: Statistic.GAUGE_PRESS,
    7: Statistic.DIFF_PRESS,
    8: Statistic.TOT_VOL,
    9: Statistic.TOT_MASS,
    10: Statistic.TOTALIZING_TIME,
    11: Statistic.BATCH_VOL_REMAIN,
    12: Statistic.BATCH_MASS_REMAIN,
    13: Statistic.VALVE_DRIVE,
    14: Statistic.TIME_MEAS_REMAIN,
    15: Statistic.BARO_PRESS,
    16: Statistic.TEMP_EXT,
    17: Statistic.VOL_FLOW_EXT,
    18: Statistic.TOT_VOL_EXT,
    19: Statistic.BATCH_VOL_EXT_REMAIN,
    20: Statistic.TEMP_EXT_VFR,
    21: Statistic.TEMP_EXT_VFR_SRC,
    25: Statistic.REL_HUM,
    26: Statistic.STATUS,
    32: Statistic.SETPT,
    34: Statistic.ABS_PRESS_SETPT,
    36: Statistic.VOL_FLOW_SETPT,
    37: Statistic.MASS_FLOW_SETPT,
    38: Statistic.GAUGE_PRESS_SETPT,
    39: Statistic.DIFF_PRESS_SETPT,
    45: Statistic.VALVE_DRIVE_SETPT,
    49: Statistic.VOL_FLOW_EXT_SETPT,
    66: Statistic.ABS_PRESS_AVG,
    67: Statistic.TEMP_STREAM_AVG,
    68: Statistic.VOL_FLOW_AVG,
    69: Statistic.MASS_FLOW_AVG,
    70: Statistic.GAUGE_PRESS_AVG,
    79: Statistic.BARO_PRESS_AVG,
    81: Statistic.VOL_FLOW_EXT_AVG,
    84: Statistic.TEMP_EXT_VFR_AVG,
    85: Statistic.TEMP_EXT_VFR_SRC_AVG,
    89: Statistic.REL_HUM_AVG,
    98: Statistic.ABS_PRESS_PEAK,
    100: Statistic.VOL_FLOW_PEAK,
    101: Statistic.MASS_FLOW_PEAK,
    102: Statistic.GAUGE_PRESS_PEAK,
    111: Statistic.BARO_PRESS_PEAK,
    113: Statistic.VOL_FLOW_EXT_PEAK,
    116: Statistic.TEMP_EXT_VFR_PEAK,
    121: Statistic.REL_HUM_PEAK,
    133: Statistic.SETPT_ERR,
    149: Statistic.ABS_PRESS_SETPT_ERR,
    150: Statistic.ABS_PRESS_MIN,
    151: Statistic.ABS_PRESS_MAX,
    158: Statistic.TEMP_STREAM_MIN,
    159: Statistic.TEMP_STREAM_MAX,
    165: Statistic.VOL_FLOW_SETPT_ERR,
    166: Statistic.VOL_FLOW_MIN,
    167: Statistic.VOL_FLOW_MAX,
    173: Statistic.MASS_FLOW_SETPT_ERR,
    174: Statistic.MASS_FLOW_MIN,
    175: Statistic.MASS_FLOW_MAX,
    181: Statistic.GAUGE_PRESS_SETPT_ERR,
    182: Statistic.GAUGE_PRESS_MIN,
    183: Statistic.GAUGE_PRESS_MAX,
    189: Statistic.DIFF_PRESS_SETPT_ERR,
    190: Statistic.DIFF_PRESS_MIN,
    191: Statistic.DIFF_PRESS_MAX,
    254: Statistic.BARO_PRESS_MIN,
    255: Statistic.BARO_PRESS_MAX,
    262: Statistic.TEMP_EXT_MIN,
    263: Statistic.TEMP_EXT_MAX,
    268: Statistic.VOL_FLOW_EXT_SETPT_ERR,
    270: Statistic.VOL_FLOW_EXT_MIN,
    271: Statistic.VOL_FLOW_EXT_MAX,
    294: Statistic.TEMP_EXT_VFR_MIN,
    295: Statistic.TEMP_EXT_VFR_MAX,
    334: Statistic.REL_HUM_MIN,
    335: Statistic.REL_HUM_MAX,
    344: Statistic.ABS_PRESS_SECOND,
    345: Statistic.ABS_PRESS_SECOND_SETPT,
    349: Statistic.ABS_PRESS_SECOND_SETPT_ERR,
    350: Statistic.ABS_PRESS_SECOND_MIN,
    351: Statistic.ABS_PRESS_SECOND_MAX,
    352: Statistic.GAUGE_PRESS_SECOND,
    353: Statistic.GAUGE_PRESS_SECOND_SETPT,
    357: Statistic.GAUGE_PRESS_SECOND_SETPT_ERR,
    358: Statistic.GAUGE_PRESS_SECOND_MIN,
    359: Statistic.GAUGE_PRESS_SECOND_MAX,
    360: Statistic.DIFF_PRESS_SECOND,
    361: Statistic.DIFF_PRESS_SECOND_SETPT,
    365: Statistic.DIFF_PRESS_SECOND_SETPT_ERR,
    366: Statistic.DIFF_PRESS_SECOND_MIN,
    367: Statistic.DIFF_PRESS_SECOND_MAX,
    392: Statistic.USER_TIME,
    400: Statistic.USER_DATE,
    703: Statistic.FLUID_NAME,
    801: Statistic.MEAS_ID,
    802: Statistic.MEAS_STAT,
}


STATISTIC_ALIASES: Final[Mapping[str, Statistic]] = {
    'None': Statistic.NONE,
    'Abs_Press': Statistic.ABS_PRESS,
    'Flow_Temp': Statistic.TEMP_STREAM,
    'Stream_Temp': Statistic.TEMP_STREAM,
    'Vol_Flow': Statistic.VOL_FLOW,
    'Volu_Flow': Statistic.VOL_FLOW,
    'Mass_Flow': Statistic.MASS_FLOW,
    'Gauge_Press': Statistic.GAUGE_PRESS,
    'Diff_Press': Statistic.DIFF_PRESS,
    'Tot_Vol': Statistic.TOT_VOL,
    'Tot_Mass': Statistic.TOT_MASS,
    'Totalizing_Time': Statistic.TOTALIZING_TIME,
    'Batch_vol_remain': Statistic.BATCH_VOL_REMAIN,
    'Batch_mass_remain': Statistic.BATCH_MASS_REMAIN,
    'Valve_Drive': Statistic.VALVE_DRIVE,
    'Remain_Time_Meas': Statistic.TIME_MEAS_REMAIN,
    'Baro_Press': Statistic.BARO_PRESS,
    'Temp_Ext': Statistic.TEMP_EXT,
    'Vol_Flow_Ext': Statistic.VOL_FLOW_EXT,
    'Tot_Vol_Ext': Statistic.TOT_VOL_EXT,
    'Batch_vol_ext_remain': Statistic.BATCH_VOL_EXT_REMAIN,
    'Ext_Vol_Flow_Ref_Temp': Statistic.TEMP_EXT_VFR,
    'Ext_Vol_Flow_Ref_Temp_Src': Statistic.TEMP_EXT_VFR_SRC,
    'Rel_Hum': Statistic.REL_HUM,
    'Relative_Humidity': Statistic.REL_HUM,
    'Status': Statistic.STATUS,
    'Setpt': Statistic.SETPT,
    'Setpoint': Statistic.SETPT,
    'Abs_Press_Setpt': Statistic.ABS_PRESS_SETPT,
    'Vol_Flow_Setpt': Statistic.VOL_FLOW_SETPT,
    'Mass_Flow_Setpt': Statistic.MASS_FLOW_SETPT,
    'Gauge_Press_Setpt': Statistic.GAUGE_PRESS_SETPT,
    'Diff_Press_Setpt': Statistic.DIFF_PRESS_SETPT,
    'Valve_Drive_Setpt': Statistic.VALVE_DRIVE_SETPT,
    'Vol_Flow_Ext_Setpt': Statistic.VOL_FLOW_EXT_SETPT,
    'Abs_Press_avg': Statistic.ABS_PRESS_AVG,
    'Flow_Temp_avg': Statistic.TEMP_STREAM_AVG,
    'Vol_Flow_avg': Statistic.VOL_FLOW_AVG,
    'Mass_Flow_avg': Statistic.MASS_FLOW_AVG,
    'Gauge_Press_avg': Statistic.GAUGE_PRESS_AVG,
    'Baro_Press_avg': Statistic.BARO_PRESS_AVG,
    'Vol_Flow_Ext_avg': Statistic.VOL_FLOW_EXT_AVG,
    'Ext_Vol_Flow_Ref_Temp_avg': Statistic.TEMP_EXT_VFR_AVG,
    'Ext_Vol_Flow_Ref_Temp_Src_avg': Statistic.TEMP_EXT_VFR_SRC_AVG,
    'Rel_Hum_avg': Statistic.REL_HUM_AVG,
    'Abs_Press_Peak': Statistic.ABS_PRESS_PEAK,
    'Vol_Flow_Peak': Statistic.VOL_FLOW_PEAK,
    'Mass_Flow_Peak': Statistic.MASS_FLOW_PEAK,
    'Gauge_Press_Peak': Statistic.GAUGE_PRESS_PEAK,
    'Baro_Press_Peak': Statistic.BARO_PRESS_PEAK,
    'Vol_Flow_Ext_Peak': Statistic.VOL_FLOW_EXT_PEAK,
    'Ext_Vol_Flow_Ref_Temp_Peak': Statistic.TEMP_EXT_VFR_PEAK,
    'Rel_Hum_Peak': Statistic.REL_HUM_PEAK,
    'Setpt_err': Statistic.SETPT_ERR,
    'Abs_Press_Setpt_err': Statistic.ABS_PRESS_SETPT_ERR,
    'Abs_Press_min': Statistic.ABS_PRESS_MIN,
    'Abs_Press_max': Statistic.ABS_PRESS_MAX,
    'Flow_Temp_min': Statistic.TEMP_STREAM_MIN,
    'Flow_Temp_max': Statistic.TEMP_STREAM_MAX,
    'Vol_Flow_Setpt_err': Statistic.VOL_FLOW_SETPT_ERR,
    'Vol_Flow_min': Statistic.VOL_FLOW_MIN,
    'Vol_Flow_max': Statistic.VOL_FLOW_MAX,
    'Mass_Flow_Setpt_err': Statistic.MASS_FLOW_SETPT_ERR,
    'Mass_Flow_min': Statistic.MASS_FLOW_MIN,
    'Mass_Flow_max': Statistic.MASS_FLOW_MAX,
    'Gauge_Press_Setpt_err': Statistic.GAUGE_PRESS_SETPT_ERR,
    'Gauge_Press_min': Statistic.GAUGE_PRESS_MIN,
    'Gauge_Press_max': Statistic.GAUGE_PRESS_MAX,
    'Diff_Press_Setpt_err': Statistic.DIFF_PRESS_SETPT_ERR,
    'Diff_Press_min': Statistic.DIFF_PRESS_MIN,
    'Diff_Press_max': Statistic.DIFF_PRESS_MAX,
    'Baro_Press_min': Statistic.BARO_PRESS_MIN,
    'Baro_Press_max': Statistic.BARO_PRESS_MAX,
    'Temp_Ext_min': Statistic.TEMP_EXT_MIN,
    'Temp_Ext_max': Statistic.TEMP_EXT_MAX,
    'Vol_Flow_Ext_Setpt_err': Statistic.VOL_FLOW_EXT_SETPT_ERR,
    'Vol_Flow_Ext_min': Statistic.VOL_FLOW_EXT_MIN,
    'Vol_Flow_Ext_max': Statistic.VOL_FLOW_EXT_MAX,
    'Ext_Vol_Flow_Ref_Temp_max': Statistic.TEMP_EXT_VFR_MAX,
    'Rel_Hum_min': Statistic.REL_HUM_MIN,
    'Rel_Hum_max': Statistic.REL_HUM_MAX,
    '2nd_Abs_Press': Statistic.ABS_PRESS_SECOND,
    '2nd_Abs_Press_Setpt': Statistic.ABS_PRESS_SECOND_SETPT,
    '2nd_Abs_Press_Setpt_err': Statistic.ABS_PRESS_SECOND_SETPT_ERR,
    '2nd_Abs_Press_min': Statistic.ABS_PRESS_SECOND_MIN,
    '2nd_Abs_Press_max': Statistic.ABS_PRESS_SECOND_MAX,
    '2nd_Gauge_Press': Statistic.GAUGE_PRESS_SECOND,
    '2nd_Gauge_Press_Setpt': Statistic.GAUGE_PRESS_SECOND_SETPT,
    '2nd_Gauge_Press_Setpt_err': Statistic.GAUGE_PRESS_SECOND_SETPT_ERR,
    '2nd_Gauge_Press_min': Statistic.GAUGE_PRESS_SECOND_MIN,
    '2nd_Gauge_Press_max': Statistic.GAUGE_PRESS_SECOND_MAX,
    '2nd_Diff_Press': Statistic.DIFF_PRESS_SECOND,
    '2nd_Diff_Press_Setpt': Statistic.DIFF_PRESS_SECOND_SETPT,
    '2nd_Diff_Press_Setpt_err': Statistic.DIFF_PRESS_SECOND_SETPT_ERR,
    '2nd_Diff_Press_min': Statistic.DIFF_PRESS_SECOND_MIN,
    '2nd_Diff_Press_max': Statistic.DIFF_PRESS_SECOND_MAX,
    'User_Time': Statistic.USER_TIME,
    'User_Date': Statistic.USER_DATE,
    'Fluid_Name': Statistic.FLUID_NAME,
    'Meas_ID': Statistic.MEAS_ID,
    'Meas_Stat': Statistic.MEAS_STAT,
}


GAS_CODES: Final[Mapping[Gas, int]] = {
    Gas.AIR: 0,
    Gas.AR: 1,
    Gas.CH4: 2,
    Gas.CO: 3,
    Gas.CO2: 4,
    Gas.C2H6: 5,
    Gas.H2: 6,
    Gas.HE: 7,
    Gas.N2: 8,
    Gas.N2O: 9,
    Gas.NE: 10,
    Gas.O2: 11,
    Gas.C3H8: 12,
    Gas.NC4H10: 13,
    Gas.C2H2: 14,
    Gas.C2H4: 15,
    Gas.IC4H10: 16,
    Gas.KR: 17,
    Gas.XE: 18,
    Gas.SF6: 19,
    Gas.C_25: 20,
    Gas.C_10: 21,
    Gas.C_8: 22,
    Gas.C_2: 23,
    Gas.C_75: 24,
    Gas.HE_25: 25,
    Gas.HE_75: 26,
    Gas.A1025: 27,
    Gas.STAR29: 28,
    Gas.P_5: 29,
    Gas.NO: 30,
    Gas.NF3: 31,
    Gas.NH3: 32,
    Gas.CL2: 33,
    Gas.H2S: 34,
    Gas.SO2: 35,
    Gas.C3H6: 36,
    Gas.BUTEN_1: 80,
    Gas.CBUTEN: 81,
    Gas.IBUTEN: 82,
    Gas.TBUTEN: 83,
    Gas.COS: 84,
    Gas.DME: 85,
    Gas.SIH4: 86,
    Gas.R_11: 100,
    Gas.R_115: 101,
    Gas.R_116: 102,
    Gas.R_124: 103,
    Gas.R_125: 104,
    Gas.R_134A: 105,
    Gas.R_14: 106,
    Gas.R_142B: 107,
    Gas.R_143A: 108,
    Gas.R_152A: 109,
    Gas.R_22: 110,
    Gas.R_23: 111,
    Gas.R_32: 112,
    Gas.R_318: 113,
    Gas.R_404A: 114,
    Gas.R_407C: 115,
    Gas.R_410A: 116,
    Gas.R_507A: 117,
    Gas.C_15: 140,
    Gas.C_20: 141,
    Gas.C_50: 142,
    Gas.HE_50: 143,
    Gas.HE_90: 144,
    Gas.BIO5M: 145,
    Gas.BIO10M: 146,
    Gas.BIO15M: 147,
    Gas.BIO20M: 148,
    Gas.BIO25M: 149,
    Gas.BIO30M: 150,
    Gas.BIO35M: 151,
    Gas.BIO40M: 152,
    Gas.BIO45M: 153,
    Gas.BIO50M: 154,
    Gas.BIO55M: 155,
    Gas.BIO60M: 156,
    Gas.BIO65M: 157,
    Gas.BIO70M: 158,
    Gas.BIO75M: 159,
    Gas.BIO80M: 160,
    Gas.BIO85M: 161,
    Gas.BIO90M: 162,
    Gas.BIO95M: 163,
    Gas.EAN_32: 164,
    Gas.EAN_36: 165,
    Gas.EAN_40: 166,
    Gas.HEOX20: 167,
    Gas.HEOX21: 168,
    Gas.HEOX30: 169,
    Gas.HEOX40: 170,
    Gas.HEOX50: 171,
    Gas.HEOX60: 172,
    Gas.HEOX80: 173,
    Gas.HEOX99: 174,
    Gas.EA_40: 175,
    Gas.EA_60: 176,
    Gas.EA_80: 177,
    Gas.METAB: 178,
    Gas.LG_4_5: 179,
    Gas.LG_6: 180,
    Gas.LG_7: 181,
    Gas.LG_9: 182,
    Gas.HENE_9: 183,
    Gas.LG_9_4: 184,
    Gas.SYNG_1: 185,
    Gas.SYNG_2: 186,
    Gas.SYNG_3: 187,
    Gas.SYNG_4: 188,
    Gas.NATG_1: 189,
    Gas.NATG_2: 190,
    Gas.NATG_3: 191,
    Gas.COALG: 192,
    Gas.ENDO: 193,
    Gas.HHO: 194,
    Gas.HD_5: 195,
    Gas.HD_10: 196,
    Gas.OCG_89: 197,
    Gas.OCG_93: 198,
    Gas.OCG_95: 199,
    Gas.FG_1: 200,
    Gas.FG_2: 201,
    Gas.FG_3: 202,
    Gas.FG_4: 203,
    Gas.FG_5: 204,
    Gas.FG_6: 205,
    Gas.P_10: 206,
    Gas.D_2: 210,
    Gas.MIX_236: 236,
    Gas.MIX_237: 237,
    Gas.MIX_238: 238,
    Gas.MIX_239: 239,
    Gas.MIX_240: 240,
    Gas.MIX_241: 241,
    Gas.MIX_242: 242,
    Gas.MIX_243: 243,
    Gas.MIX_244: 244,
    Gas.MIX_245: 245,
    Gas.MIX_246: 246,
    Gas.MIX_247: 247,
    Gas.MIX_248: 248,
    Gas.MIX_249: 249,
    Gas.MIX_250: 250,
    Gas.MIX_251: 251,
    Gas.MIX_252: 252,
    Gas.MIX_253: 253,
    Gas.MIX_254: 254,
    Gas.MIX_255: 255,
}


GAS_DISPLAY_NAMES: Final[Mapping[Gas, str]] = {
    Gas.AIR: 'Air (Clean Dry)',
    Gas.AR: 'Argon',
    Gas.CH4: 'Methane',
    Gas.CO: 'Carbon Monoxide',
    Gas.CO2: 'Carbon Dioxide',
    Gas.C2H6: 'Ethane',
    Gas.H2: 'Hydrogen',
    Gas.HE: 'Helium',
    Gas.N2: 'Nitrogen',
    Gas.N2O: 'Nitrous Oxide',
    Gas.NE: 'Neon',
    Gas.O2: 'Oxygen',
    Gas.C3H8: 'Propane',
    Gas.NC4H10: 'Normal Butane',
    Gas.C2H2: 'Acetylene',
    Gas.C2H4: 'Ethylene (Ethene)',
    Gas.IC4H10: 'Isobutane',
    Gas.KR: 'Krypton',
    Gas.XE: 'Xenon',
    Gas.SF6: 'Sulfur Hexafluoride',
    Gas.C_25: '25% CO2, 75% Ar',
    Gas.C_10: '10% CO2, 90% Ar',
    Gas.C_8: '8% CO2, 92% Ar',
    Gas.C_2: '2% CO2, 98% Ar',
    Gas.C_75: '75% CO2, 25% Ar',
    Gas.HE_25: '25% He, 75% Ar',
    Gas.HE_75: '75% He, 25% Ar',
    Gas.A1025: '90% He, 7.5% Ar, 2.5% CO2',
    Gas.STAR29: 'Stargon CS (90% Ar, 8% CO2, 2% O2)',
    Gas.P_5: '5% CH4, 95% Ar',
    Gas.NO: 'Nitric Oxide',
    Gas.NF3: 'Nitrogen Trifluoride',
    Gas.NH3: 'Ammonia',
    Gas.CL2: 'Chlorine',
    Gas.H2S: 'Hydrogen Sulfide',
    Gas.SO2: 'Sulfur Dioxide',
    Gas.C3H6: 'Propylene',
    Gas.BUTEN_1: '1-Butylene',
    Gas.CBUTEN: 'Cis-Butene (cis-2-Butene)',
    Gas.IBUTEN: 'Isobutene',
    Gas.TBUTEN: 'Trans-2-Butene',
    Gas.COS: 'Carbonyl Sulfide',
    Gas.DME: 'Dimethylether (C2H6O)',
    Gas.SIH4: 'Silane',
    Gas.R_11: 'Trichlorofluoromethane (CCl3F)',
    Gas.R_115: 'Chloropentafluoroethane (C2ClF5)',
    Gas.R_116: 'Hexafluoroethane (C2F6)',
    Gas.R_124: 'Chlorotetrafluoroethane (C2HClF4)',
    Gas.R_125: 'Pentafluoroethane (CF3CHF2)',
    Gas.R_134A: 'Tetrafluoroethane (CH2FCF3)',
    Gas.R_14: 'Tetrafluoromethane (CF4)',
    Gas.R_142B: 'Chlorodifluoroethane (CH3CClF2)',
    Gas.R_143A: 'Trifluoroethane (C2H3F3)',
    Gas.R_152A: 'Difluoroethane (C2H4F2)',
    Gas.R_22: 'Difluoromonochloromethane (CHClF2)',
    Gas.R_23: 'Trifluoromethane (CHF3)',
    Gas.R_32: 'Difluoromethane (CH2F2)',
    Gas.R_318: 'Octafluorocyclobutane (C4F8)',
    Gas.R_404A: '44% R-125, 4% R-134A, 52% R-143A',
    Gas.R_407C: '23% R-32, 25% R-125, 52% R-143A',
    Gas.R_410A: '50% R-32, 50% R-125',
    Gas.R_507A: '50% R-125, 50% R-143A',
    Gas.C_15: '15% CO2, 85% Ar',
    Gas.C_20: '20% CO2, 80% Ar',
    Gas.C_50: '50% CO2, 50% Ar',
    Gas.HE_50: '50% He, 50% Ar',
    Gas.HE_90: '90% He, 10% Ar',
    Gas.BIO5M: '5% CH4, 95% CO2',
    Gas.BIO10M: '10% CH4, 90% CO2',
    Gas.BIO15M: '15% CH4, 85% CO2',
    Gas.BIO20M: '20% CH4, 80% CO2',
    Gas.BIO25M: '25% CH4, 75% CO2',
    Gas.BIO30M: '30% CH4, 70% CO2',
    Gas.BIO35M: '35% CH4, 65% CO2',
    Gas.BIO40M: '40% CH4, 60% CO2',
    Gas.BIO45M: '45% CH4, 55% CO2',
    Gas.BIO50M: '50% CH4, 50% CO2',
    Gas.BIO55M: '55% CH4, 45% CO2',
    Gas.BIO60M: '60% CH4, 40% CO2',
    Gas.BIO65M: '65% CH4, 35% CO2',
    Gas.BIO70M: '70% CH4, 30% CO2',
    Gas.BIO75M: '75% CH4, 25% CO2',
    Gas.BIO80M: '80% CH4, 20% CO2',
    Gas.BIO85M: '85% CH4, 15% CO2',
    Gas.BIO90M: '90% CH4, 10% CO2',
    Gas.BIO95M: '95% CH4, 5% CO2',
    Gas.EAN_32: '32% O2, 68% N2',
    Gas.EAN_36: '36% O2, 64% N2',
    Gas.EAN_40: '40% O2, 60% N2',
    Gas.HEOX20: '20% O2, 80% He',
    Gas.HEOX21: '21% O2, 79% He',
    Gas.HEOX30: '30% O2, 70% He',
    Gas.HEOX40: '40% O2, 60% He',
    Gas.HEOX50: '50% O2, 50% He',
    Gas.HEOX60: '60% O2, 40% He',
    Gas.HEOX80: '80% O2, 20% He',
    Gas.HEOX99: '99% O2, 1% He',
    Gas.EA_40: 'Enriched Air-40% O2',
    Gas.EA_60: 'Enriched Air-60% O2',
    Gas.EA_80: 'Enriched Air-80% O2',
    Gas.METAB: 'Metabolic Exhalant (16% O2, 78.04% N2, 5% CO2, 0.96% Ar)',
    Gas.LG_4_5: '4.5% CO2, 13.5% N2, 82% He',
    Gas.LG_6: '6% CO2, 14% N2, 80% He',
    Gas.LG_7: '7% CO2, 14% N2, 79% He',
    Gas.LG_9: '9% CO2, 15% N2, 76% He',
    Gas.HENE_9: '9% Ne, 91% He',
    Gas.LG_9_4: '9.4% CO2, 19.25% N2, 71.35% He',
    Gas.SYNG_1: '40% H2, 29% CO, 20% CO2, 11% CH4',
    Gas.SYNG_2: '64% H2, 28% CO, 1% CO2, 7% CH4',
    Gas.SYNG_3: '70% H2, 4% CO, 25% CO2, 1% CH4',
    Gas.SYNG_4: '83% H2, 14% CO, 3% CH4',
    Gas.NATG_1: '93% CH4, 3% C2H6, 1% C3H8, 2% N2, 1% CO2',
    Gas.NATG_2: '95% CH4, 3% C2H6, 1% N2, 1% CO2',
    Gas.NATG_3: '95.2% CH4, 2.5% C2H6, 0.2% C3H8, 0.1% C4H10, 1.3% N2, 0.7% CO2',
    Gas.COALG: '50% H2, 35% CH4, 10% CO, 5% C2H4',
    Gas.ENDO: '75% H2, 25% N2',
    Gas.HHO: '66.67% H2, 33.33% O2',
    Gas.HD_5: 'LPG: 96.1% C3H8, 1.5% C2H6, 0.4% C3H6, 1.9% n-C4H10',
    Gas.HD_10: 'LPG: 85% C3H8, 10% C3H6, 5% n-C4H10',
    Gas.OCG_89: '89% O2, 7% N2, 4% Ar',
    Gas.OCG_93: '93% O2, 3% N2, 4% Ar',
    Gas.OCG_95: '95% O2, 1% N2, 4% Ar',
    Gas.FG_1: '2.5% O2, 10.8% CO2, 85.7% N2, 1% Ar',
    Gas.FG_2: '2.9% O2, 14% CO2, 82.1% N2, 1% Ar',
    Gas.FG_3: '3.7% O2, 15% CO2, 80.3% N2, 1% Ar',
    Gas.FG_4: '7% O2, 12% CO2, 80% N2, 1% Ar',
    Gas.FG_5: '10% O2, 9.5% CO2, 79.5% N2, 1% Ar',
    Gas.FG_6: '13% O2, 7% CO2, 79% N2, 1% Ar',
    Gas.P_10: '10% CH4, 90% Ar',
    Gas.D_2: 'Deuterium',
    Gas.MIX_236: 'Custom gas mixture slot 236',
    Gas.MIX_237: 'Custom gas mixture slot 237',
    Gas.MIX_238: 'Custom gas mixture slot 238',
    Gas.MIX_239: 'Custom gas mixture slot 239',
    Gas.MIX_240: 'Custom gas mixture slot 240',
    Gas.MIX_241: 'Custom gas mixture slot 241',
    Gas.MIX_242: 'Custom gas mixture slot 242',
    Gas.MIX_243: 'Custom gas mixture slot 243',
    Gas.MIX_244: 'Custom gas mixture slot 244',
    Gas.MIX_245: 'Custom gas mixture slot 245',
    Gas.MIX_246: 'Custom gas mixture slot 246',
    Gas.MIX_247: 'Custom gas mixture slot 247',
    Gas.MIX_248: 'Custom gas mixture slot 248',
    Gas.MIX_249: 'Custom gas mixture slot 249',
    Gas.MIX_250: 'Custom gas mixture slot 250',
    Gas.MIX_251: 'Custom gas mixture slot 251',
    Gas.MIX_252: 'Custom gas mixture slot 252',
    Gas.MIX_253: 'Custom gas mixture slot 253',
    Gas.MIX_254: 'Custom gas mixture slot 254',
    Gas.MIX_255: 'Custom gas mixture slot 255',
}


GAS_BY_CODE: Final[Mapping[int, Gas]] = {
    0: Gas.AIR,
    1: Gas.AR,
    2: Gas.CH4,
    3: Gas.CO,
    4: Gas.CO2,
    5: Gas.C2H6,
    6: Gas.H2,
    7: Gas.HE,
    8: Gas.N2,
    9: Gas.N2O,
    10: Gas.NE,
    11: Gas.O2,
    12: Gas.C3H8,
    13: Gas.NC4H10,
    14: Gas.C2H2,
    15: Gas.C2H4,
    16: Gas.IC4H10,
    17: Gas.KR,
    18: Gas.XE,
    19: Gas.SF6,
    20: Gas.C_25,
    21: Gas.C_10,
    22: Gas.C_8,
    23: Gas.C_2,
    24: Gas.C_75,
    25: Gas.HE_25,
    26: Gas.HE_75,
    27: Gas.A1025,
    28: Gas.STAR29,
    29: Gas.P_5,
    30: Gas.NO,
    31: Gas.NF3,
    32: Gas.NH3,
    33: Gas.CL2,
    34: Gas.H2S,
    35: Gas.SO2,
    36: Gas.C3H6,
    80: Gas.BUTEN_1,
    81: Gas.CBUTEN,
    82: Gas.IBUTEN,
    83: Gas.TBUTEN,
    84: Gas.COS,
    85: Gas.DME,
    86: Gas.SIH4,
    100: Gas.R_11,
    101: Gas.R_115,
    102: Gas.R_116,
    103: Gas.R_124,
    104: Gas.R_125,
    105: Gas.R_134A,
    106: Gas.R_14,
    107: Gas.R_142B,
    108: Gas.R_143A,
    109: Gas.R_152A,
    110: Gas.R_22,
    111: Gas.R_23,
    112: Gas.R_32,
    113: Gas.R_318,
    114: Gas.R_404A,
    115: Gas.R_407C,
    116: Gas.R_410A,
    117: Gas.R_507A,
    140: Gas.C_15,
    141: Gas.C_20,
    142: Gas.C_50,
    143: Gas.HE_50,
    144: Gas.HE_90,
    145: Gas.BIO5M,
    146: Gas.BIO10M,
    147: Gas.BIO15M,
    148: Gas.BIO20M,
    149: Gas.BIO25M,
    150: Gas.BIO30M,
    151: Gas.BIO35M,
    152: Gas.BIO40M,
    153: Gas.BIO45M,
    154: Gas.BIO50M,
    155: Gas.BIO55M,
    156: Gas.BIO60M,
    157: Gas.BIO65M,
    158: Gas.BIO70M,
    159: Gas.BIO75M,
    160: Gas.BIO80M,
    161: Gas.BIO85M,
    162: Gas.BIO90M,
    163: Gas.BIO95M,
    164: Gas.EAN_32,
    165: Gas.EAN_36,
    166: Gas.EAN_40,
    167: Gas.HEOX20,
    168: Gas.HEOX21,
    169: Gas.HEOX30,
    170: Gas.HEOX40,
    171: Gas.HEOX50,
    172: Gas.HEOX60,
    173: Gas.HEOX80,
    174: Gas.HEOX99,
    175: Gas.EA_40,
    176: Gas.EA_60,
    177: Gas.EA_80,
    178: Gas.METAB,
    179: Gas.LG_4_5,
    180: Gas.LG_6,
    181: Gas.LG_7,
    182: Gas.LG_9,
    183: Gas.HENE_9,
    184: Gas.LG_9_4,
    185: Gas.SYNG_1,
    186: Gas.SYNG_2,
    187: Gas.SYNG_3,
    188: Gas.SYNG_4,
    189: Gas.NATG_1,
    190: Gas.NATG_2,
    191: Gas.NATG_3,
    192: Gas.COALG,
    193: Gas.ENDO,
    194: Gas.HHO,
    195: Gas.HD_5,
    196: Gas.HD_10,
    197: Gas.OCG_89,
    198: Gas.OCG_93,
    199: Gas.OCG_95,
    200: Gas.FG_1,
    201: Gas.FG_2,
    202: Gas.FG_3,
    203: Gas.FG_4,
    204: Gas.FG_5,
    205: Gas.FG_6,
    206: Gas.P_10,
    210: Gas.D_2,
    236: Gas.MIX_236,
    237: Gas.MIX_237,
    238: Gas.MIX_238,
    239: Gas.MIX_239,
    240: Gas.MIX_240,
    241: Gas.MIX_241,
    242: Gas.MIX_242,
    243: Gas.MIX_243,
    244: Gas.MIX_244,
    245: Gas.MIX_245,
    246: Gas.MIX_246,
    247: Gas.MIX_247,
    248: Gas.MIX_248,
    249: Gas.MIX_249,
    250: Gas.MIX_250,
    251: Gas.MIX_251,
    252: Gas.MIX_252,
    253: Gas.MIX_253,
    254: Gas.MIX_254,
    255: Gas.MIX_255,
}


GAS_ALIASES: Final[Mapping[str, Gas]] = {
    'Argon': Gas.AR,
    'Methane': Gas.CH4,
    'Carbon Monoxide': Gas.CO,
    'Carbon_Monoxide': Gas.CO,
    'Carbon Dioxide': Gas.CO2,
    'Carbon_Dioxide': Gas.CO2,
    'Ethane': Gas.C2H6,
    'Hydrogen': Gas.H2,
    'Helium': Gas.HE,
    'Nitrogen': Gas.N2,
    'Nitrous Oxide': Gas.N2O,
    'Nitrous_Oxide': Gas.N2O,
    'Neon': Gas.NE,
    'Oxygen': Gas.O2,
    'Propane': Gas.C3H8,
    'n-Butane': Gas.NC4H10,
    'Butane': Gas.NC4H10,
    'C4H10': Gas.NC4H10,
    'Acetylene': Gas.C2H2,
    'Ethylene': Gas.C2H4,
    'Ethene': Gas.C2H4,
    'Isobutane': Gas.IC4H10,
    'i-C4H10': Gas.IC4H10,
    'Krypton': Gas.KR,
    'Xenon': Gas.XE,
    'Sulfur Hexafluoride': Gas.SF6,
    'Sulfur_Hexafluoride': Gas.SF6,
    '25%_CO2,_75%_Ar': Gas.C_25,
    '10%_CO2,_90%_Ar': Gas.C_10,
    '8%_CO2,_92%_Ar': Gas.C_8,
    '2%_CO2,_98%_Ar': Gas.C_2,
    '75%_CO2,_25%_Ar': Gas.C_75,
    '25%_He,_75%_Ar': Gas.HE_25,
    '75%_He,_25%_Ar': Gas.HE_75,
    '90%_He,_7.5%_Ar,_2.5%_CO2': Gas.A1025,
    'Stargon CS': Gas.STAR29,
    'Stargon_CS': Gas.STAR29,
    '5%_CH4,_95%_Ar': Gas.P_5,
    'Nitric Oxide': Gas.NO,
    'Nitric_Oxide': Gas.NO,
    'Nitrogen Trifluoride': Gas.NF3,
    'Nitrogen_Trifluoride': Gas.NF3,
    'Ammonia': Gas.NH3,
    'Chlorine': Gas.CL2,
    'Hydrogen Sulfide': Gas.H2S,
    'Hydrogen_Sulfide': Gas.H2S,
    'Hydrogen_Sulphide': Gas.H2S,
    'Sulfur Dioxide': Gas.SO2,
    'Sulfur_Dioxide': Gas.SO2,
    'Propylene': Gas.C3H6,
    '1-Butylene': Gas.BUTEN_1,
    '1Butene': Gas.BUTEN_1,
    'Cis-Butene': Gas.CBUTEN,
    'cButene': Gas.CBUTEN,
    'cis-2-Butene': Gas.CBUTEN,
    'Isobutene': Gas.IBUTEN,
    'Trans-2-Butene': Gas.TBUTEN,
    'Carbonyl Sulfide': Gas.COS,
    'Carbonyl_Sulfide': Gas.COS,
    'Dimethylether': Gas.DME,
    'C2H6O': Gas.DME,
    'DMES': Gas.DME,
    'Silane': Gas.SIH4,
    'CCl3F': Gas.R_11,
    'Trichlorofluoromethane': Gas.R_11,
    'C2ClF5': Gas.R_115,
    'Chloropentafluoroethane': Gas.R_115,
    'Chloroppentafluoroethane': Gas.R_115,
    'C2F6': Gas.R_116,
    'Hexafluoroethane': Gas.R_116,
    'C2HClF4': Gas.R_124,
    'Chlorotetrafluoroethane': Gas.R_124,
    'CF3CHF2': Gas.R_125,
    'Pentafluoroethane': Gas.R_125,
    'CH2FCF3': Gas.R_134A,
    'Tetrafluoroethane': Gas.R_134A,
    'R-134a': Gas.R_134A,
    'CF4': Gas.R_14,
    'Tetrafluoromethane': Gas.R_14,
    'CH3CClF2': Gas.R_142B,
    'Chlorodifluoroethane': Gas.R_142B,
    'R-142B': Gas.R_142B,
    'C2H3F3': Gas.R_143A,
    'Trifluoroethane': Gas.R_143A,
    'R-143A': Gas.R_143A,
    'C2H4F2': Gas.R_152A,
    'Difluoroethane': Gas.R_152A,
    'R-152A': Gas.R_152A,
    'CHClF2': Gas.R_22,
    'Difluoromonochloromethane': Gas.R_22,
    'CHF3': Gas.R_23,
    'Trifluoromethane': Gas.R_23,
    'CH2F2': Gas.R_32,
    'Difluoromethane': Gas.R_32,
    'C4F8': Gas.R_318,
    'Octafluorocyclobutane': Gas.R_318,
    '44%_R-125,_4%_R-134A,_52%_R-143A': Gas.R_404A,
    '23%_R-32,_25%_R-125,_52%_R-143A': Gas.R_407C,
    '50%_R-32,_50%_R-125': Gas.R_410A,
    '50%_R-125,_50%_R-143A': Gas.R_507A,
    '15%_CO2,_85%_Ar': Gas.C_15,
    '20%_CO2,_80%_Ar': Gas.C_20,
    '50%_CO2,_50%_Ar': Gas.C_50,
    '50%_He,_50%_Ar': Gas.HE_50,
    '90%_He,_10%_Ar': Gas.HE_90,
    '5%_CH4,_95%_CO2': Gas.BIO5M,
    '10%_CH4,_90%_CO2': Gas.BIO10M,
    '15%_CH4,_85%_CO2': Gas.BIO15M,
    '20%_CH4,_80%_CO2': Gas.BIO20M,
    '25%_CH4,_75%_CO2': Gas.BIO25M,
    '30%_CH4,_70%_CO2': Gas.BIO30M,
    '35%_CH4,_65%_CO2': Gas.BIO35M,
    '40%_CH4,_60%_CO2': Gas.BIO40M,
    '45%_CH4,_55%_CO2': Gas.BIO45M,
    '50%_CH4,_50%_CO2': Gas.BIO50M,
    '55%_CH4,_45%_CO2': Gas.BIO55M,
    '60%_CH4,_40%_CO2': Gas.BIO60M,
    '65%_CH4,_35%_CO2': Gas.BIO65M,
    '70%_CH4,_30%_CO2': Gas.BIO70M,
    '75%_CH4,_25%_CO2': Gas.BIO75M,
    '80%_CH4,_20%_CO2': Gas.BIO80M,
    '85%_CH4,_15%_CO2': Gas.BIO85M,
    '90%_CH4,_10%_CO2': Gas.BIO90M,
    '95%_CH4,_5%_CO2': Gas.BIO95M,
    '32%_O2,_68%_N2': Gas.EAN_32,
    '36%_O2,_64%_N2': Gas.EAN_36,
    '40%_O2,_60%_N2': Gas.EAN_40,
    '20%_O2,_80%_He': Gas.HEOX20,
    '21%_O2,_79%_He': Gas.HEOX21,
    '30%_O2,_70%_He': Gas.HEOX30,
    '40%_O2,_60%_He': Gas.HEOX40,
    '50%_O2,_50%_He': Gas.HEOX50,
    '60%_O2,_40%_He': Gas.HEOX60,
    '80%_O2,_20%_He': Gas.HEOX80,
    '99%_O2,_1%_He': Gas.HEOX99,
    'Enriched_Air_40%_O2': Gas.EA_40,
    'Enriched_Air_60%_O2': Gas.EA_60,
    'Enriched_Air_80%_O2': Gas.EA_80,
    'Metabolic_Exhalant': Gas.METAB,
    '16%_O2,_78.04%_N2,_5%_CO2,_0.96%_Ar': Gas.METAB,
    '4.5%_CO2,_13.5%_N2,_82%_He': Gas.LG_4_5,
    '6%_CO2,_14%_N2,_80%_He': Gas.LG_6,
    '7%_CO2,_14%_N2,_79%_He': Gas.LG_7,
    '9%_CO2,_15%_N2,_76%_He': Gas.LG_9,
    'HeNe9': Gas.HENE_9,
    '9%_Ne,_91%_He': Gas.HENE_9,
    '9.4%_CO2,_19.25%_N2,_71.35%_He': Gas.LG_9_4,
    '40%_H2,_29%_CO,_20%_CO2,_11%_CH4': Gas.SYNG_1,
    '64%_H2,_28%_CO,_1%_CO2,_7%_CH4': Gas.SYNG_2,
    '70%_H2,_4%_CO,_25%_CO2,_1%_CH4': Gas.SYNG_3,
    '83%_H2,_14%_CO,_3%_CH4': Gas.SYNG_4,
    '93%_CH4,_3%_C2H6,_1%_C3H8,_2%_N2,_1%_CO2': Gas.NATG_1,
    '95%_CH4,_3%_C2H6,_1%_N2,_1%_CO2': Gas.NATG_2,
    '95.2%_CH4,_2.5%_C2H6,_0.2%_C3H8,_0.1%_C4H10,_1.3%_N2,_0.7%_CO2': Gas.NATG_3,
    '50%_H2,_35%_CH4,_10%_CO,_5%_C2H4': Gas.COALG,
    '75%_H2,_25%_N2': Gas.ENDO,
    '66.67%_H2,_33.33%_O2': Gas.HHO,
    'LPG:_96.1%_C3H8,_1.5%_C2H6,_0.4%_C3H6,_1.9%_n-C4H10': Gas.HD_5,
    'LPG:_85%_C3H8,_10%_C3H6,_5%_n-C4H10': Gas.HD_10,
    '89%_O2,_7%_N2,_4%_Ar': Gas.OCG_89,
    '93%_O2,_3%_N2,_4%_Ar': Gas.OCG_93,
    '95%_O2,_1%_N2,_4%_Ar': Gas.OCG_95,
    '2.5%_O2,_10.8%_CO2,_85.7%_N2,_1%_Ar': Gas.FG_1,
    '2.9%_O2,_14%_CO2,_82.1%_N2,_1%_Ar': Gas.FG_2,
    '3.7%_O2,_15%_CO2,_80.3%_N2,_1%_Ar': Gas.FG_3,
    '7%_O2,_12%_CO2,_80%_N2,_1%_Ar': Gas.FG_4,
    '10%_O2,_9.5%_CO2,_79.5%_N2,_1%_Ar': Gas.FG_5,
    '13%_O2,_7%_CO2,_79%_N2,_1%_Ar': Gas.FG_6,
    '10%_CH4,_90%_Ar': Gas.P_10,
    'Deuterium': Gas.D_2,
    '236': Gas.MIX_236,
    '237': Gas.MIX_237,
    '238': Gas.MIX_238,
    '239': Gas.MIX_239,
    '240': Gas.MIX_240,
    '241': Gas.MIX_241,
    '242': Gas.MIX_242,
    '243': Gas.MIX_243,
    '244': Gas.MIX_244,
    '245': Gas.MIX_245,
    '246': Gas.MIX_246,
    '247': Gas.MIX_247,
    '248': Gas.MIX_248,
    '249': Gas.MIX_249,
    '250': Gas.MIX_250,
    '251': Gas.MIX_251,
    '252': Gas.MIX_252,
    '253': Gas.MIX_253,
    '254': Gas.MIX_254,
    '255': Gas.MIX_255,
}


UNIT_CODES: Final[Mapping[Unit, int]] = {
    Unit.DEFAULT: 0,
    Unit.UNKNOWN: 1,
    Unit.COUNT: 62,
    Unit.PERCENT: 63,
    Unit.SUL_M: 2,
    Unit.SML_S: 3,
    Unit.SML_M: 4,
    Unit.SML_H: 5,
    Unit.SL_S: 6,
    Unit.SLPM: 7,
    Unit.SL_H: 8,
    Unit.SCCS: 11,
    Unit.SCCM: 12,
    Unit.SCM3_H: 13,
    Unit.SM3_M: 14,
    Unit.SM3_H: 15,
    Unit.SM3_D: 16,
    Unit.SIN3_M: 17,
    Unit.SCFM: 18,
    Unit.SCFH: 19,
    Unit.KSCFM: 20,
    Unit.SCFD: 21,
    Unit.NUL_M: 32,
    Unit.NML_S: 33,
    Unit.NML_M: 34,
    Unit.NML_H: 35,
    Unit.NL_S: 36,
    Unit.NLPM: 37,
    Unit.NL_H: 38,
    Unit.NCCS: 41,
    Unit.NCCM: 42,
    Unit.NCM3_H: 43,
    Unit.NM3_M: 44,
    Unit.NM3_H: 45,
    Unit.NM3_D: 46,
    Unit.MG_S: 64,
    Unit.MG_M: 65,
    Unit.G_S: 66,
    Unit.G_M: 67,
    Unit.G_H: 68,
    Unit.KG_M: 69,
    Unit.KG_H: 70,
    Unit.OZ_S: 71,
    Unit.OZ_M: 72,
    Unit.LB_M: 73,
    Unit.LB_H: 74,
    Unit.SUL: 2,
    Unit.SML: 3,
    Unit.SL: 4,
    Unit.SCM3: 6,
    Unit.SM3: 7,
    Unit.SIN3: 8,
    Unit.SFT3: 9,
    Unit.KSFT3: 10,
    Unit.NUL: 32,
    Unit.NML: 33,
    Unit.NL: 34,
    Unit.NCM3: 36,
    Unit.NM3: 37,
    Unit.UL_M: 2,
    Unit.ML_S: 3,
    Unit.ML_M: 4,
    Unit.ML_H: 5,
    Unit.L_S: 6,
    Unit.LPM: 7,
    Unit.L_H: 8,
    Unit.US_GPM: 9,
    Unit.US_GPH: 10,
    Unit.CCS: 11,
    Unit.CCM: 12,
    Unit.CM3_H: 13,
    Unit.M3_M: 14,
    Unit.M3_H: 15,
    Unit.M3_D: 16,
    Unit.IN3_M: 17,
    Unit.CFM: 18,
    Unit.CFH: 19,
    Unit.CFD: 21,
    Unit.UL: 2,
    Unit.ML: 3,
    Unit.L: 4,
    Unit.US_GAL: 5,
    Unit.CM3: 6,
    Unit.M3: 7,
    Unit.IN3: 8,
    Unit.FT3: 9,
    Unit.UP: 61,
    Unit.PA: 2,
    Unit.HPA: 3,
    Unit.KPA: 4,
    Unit.MPA: 5,
    Unit.MBAR: 6,
    Unit.BAR: 7,
    Unit.G_CM2: 8,
    Unit.KG_CM2: 9,
    Unit.PSI: 10,
    Unit.PSF: 11,
    Unit.MTORR: 12,
    Unit.TORR: 13,
    Unit.MMHG: 14,
    Unit.INHG: 15,
    Unit.MMH2O: 16,
    Unit.MMH2O_60F: 17,
    Unit.CMH2O: 18,
    Unit.CMH2O_60F: 19,
    Unit.INH2O: 20,
    Unit.INH2O_60F: 21,
    Unit.ATM: 22,
    Unit.V: 61,
    Unit.DEG_C: 2,
    Unit.DEG_F: 3,
    Unit.DEG_K: 4,
    Unit.DEG_RA: 5,
    Unit.H_M_S: 2,
    Unit.MS: 3,
    Unit.S: 4,
    Unit.M: 5,
    Unit.HOUR: 6,
    Unit.DAY: 7,
}


UNIT_DISPLAY_NAMES: Final[Mapping[Unit, str]] = {
    Unit.DEFAULT: 'Unit not specified; use default',
    Unit.UNKNOWN: 'Unknown unit; no conversions performed',
    Unit.COUNT: 'Setpoint count (0–64000)',
    Unit.PERCENT: 'Percent of full scale',
    Unit.SUL_M: 'Standard microliter per minute',
    Unit.SML_S: 'Standard milliliter per second',
    Unit.SML_M: 'Standard milliliter per minute',
    Unit.SML_H: 'Standard milliliter per hour',
    Unit.SL_S: 'Standard liter per second',
    Unit.SLPM: 'Standard liter per minute',
    Unit.SL_H: 'Standard liter per hour',
    Unit.SCCS: 'Standard cubic centimeter per second',
    Unit.SCCM: 'Standard cubic centimeter per minute',
    Unit.SCM3_H: 'Standard cubic centimeter per hour',
    Unit.SM3_M: 'Standard cubic meter per minute',
    Unit.SM3_H: 'Standard cubic meter per hour',
    Unit.SM3_D: 'Standard cubic meter per day',
    Unit.SIN3_M: 'Standard cubic inch per minute',
    Unit.SCFM: 'Standard cubic foot per minute',
    Unit.SCFH: 'Standard cubic foot per hour',
    Unit.KSCFM: '1000 standard cubic feet per minute',
    Unit.SCFD: 'Standard cubic foot per day',
    Unit.NUL_M: 'Normal microliter per minute',
    Unit.NML_S: 'Normal milliliter per second',
    Unit.NML_M: 'Normal milliliter per minute',
    Unit.NML_H: 'Normal milliliter per hour',
    Unit.NL_S: 'Normal liter per second',
    Unit.NLPM: 'Normal liter per minute',
    Unit.NL_H: 'Normal liter per hour',
    Unit.NCCS: 'Normal cubic centimeter per second',
    Unit.NCCM: 'Normal cubic centimeter per minute',
    Unit.NCM3_H: 'Normal cubic centimeter per hour',
    Unit.NM3_M: 'Normal cubic meter per minute',
    Unit.NM3_H: 'Normal cubic meter per hour',
    Unit.NM3_D: 'Normal cubic meter per day',
    Unit.MG_S: 'Milligram per second',
    Unit.MG_M: 'Milligram per minute',
    Unit.G_S: 'Gram per second',
    Unit.G_M: 'Gram per minute',
    Unit.G_H: 'Gram per hour',
    Unit.KG_M: 'Kilogram per minute',
    Unit.KG_H: 'Kilogram per hour',
    Unit.OZ_S: 'Ounce per second',
    Unit.OZ_M: 'Ounce per minute',
    Unit.LB_M: 'Pound per minute',
    Unit.LB_H: 'Pound per hour',
    Unit.SUL: 'Standard microliter',
    Unit.SML: 'Standard milliliter',
    Unit.SL: 'Standard liter',
    Unit.SCM3: 'Standard cubic centimeter',
    Unit.SM3: 'Standard cubic meter',
    Unit.SIN3: 'Standard cubic inch',
    Unit.SFT3: 'Standard cubic foot',
    Unit.KSFT3: '1000 standard cubic feet',
    Unit.NUL: 'Normal microliter',
    Unit.NML: 'Normal milliliter',
    Unit.NL: 'Normal liter',
    Unit.NCM3: 'Normal cubic centimeter',
    Unit.NM3: 'Normal cubic meter',
    Unit.UL_M: 'Microliter per minute',
    Unit.ML_S: 'Milliliter per second',
    Unit.ML_M: 'Milliliter per minute',
    Unit.ML_H: 'Milliliter per hour',
    Unit.L_S: 'Liter per second',
    Unit.LPM: 'Liter per minute',
    Unit.L_H: 'Liter per hour',
    Unit.US_GPM: 'US gallon per minute',
    Unit.US_GPH: 'US gallon per hour',
    Unit.CCS: 'Cubic centimeter per second',
    Unit.CCM: 'Cubic centimeter per minute',
    Unit.CM3_H: 'Cubic centimeter per hour',
    Unit.M3_M: 'Cubic meter per minute',
    Unit.M3_H: 'Cubic meter per hour',
    Unit.M3_D: 'Cubic meter per day',
    Unit.IN3_M: 'Cubic inch per minute',
    Unit.CFM: 'Cubic foot per minute',
    Unit.CFH: 'Cubic foot per hour',
    Unit.CFD: 'Cubic foot per day',
    Unit.UL: 'Microliter',
    Unit.ML: 'Milliliter',
    Unit.L: 'Liter',
    Unit.US_GAL: 'US gallon',
    Unit.CM3: 'Cubic centimeter',
    Unit.M3: 'Cubic meter',
    Unit.IN3: 'Cubic inch',
    Unit.FT3: 'Cubic foot',
    Unit.UP: 'Micropoise',
    Unit.PA: 'Pascal',
    Unit.HPA: 'Hectopascal',
    Unit.KPA: 'Kilopascal',
    Unit.MPA: 'Megapascal',
    Unit.MBAR: 'Millibar',
    Unit.BAR: 'Bar',
    Unit.G_CM2: 'Gram-force per square centimeter',
    Unit.KG_CM2: 'Kilogram-force per square centimeter',
    Unit.PSI: 'Pound-force per square inch',
    Unit.PSF: 'Pound-force per square foot',
    Unit.MTORR: 'Millitorr',
    Unit.TORR: 'Torr',
    Unit.MMHG: 'Millimeter of mercury at 0°C',
    Unit.INHG: 'Inch of mercury at 0°C',
    Unit.MMH2O: 'Millimeter of water at 4°C (NIST conventional)',
    Unit.MMH2O_60F: 'Millimeter of water at 60°F',
    Unit.CMH2O: 'Centimeter of water at 4°C (NIST conventional)',
    Unit.CMH2O_60F: 'Centimeter of water at 60°F',
    Unit.INH2O: 'Inch of water at 4°C (NIST conventional)',
    Unit.INH2O_60F: 'Inch of water at 60°F',
    Unit.ATM: 'Atmosphere',
    Unit.V: 'Volt (log-linear abs pressure sensors)',
    Unit.DEG_C: 'Degree Celsius',
    Unit.DEG_F: 'Degree Fahrenheit',
    Unit.DEG_K: 'Kelvin',
    Unit.DEG_RA: 'Degree Rankine',
    Unit.H_M_S: 'Hours:minutes:seconds',
    Unit.MS: 'Millisecond',
    Unit.S: 'Second',
    Unit.M: 'Minute',
    Unit.HOUR: 'Hour',
    Unit.DAY: 'Day',
}


UNIT_CATEGORIES: Final[Mapping[Unit, frozenset[UnitCategory]]] = {
    Unit.DEFAULT: frozenset({UnitCategory.STD_NORM_FLOW, UnitCategory.TOTAL_STD_NORM_VOLUME, UnitCategory.VOLUMETRIC_FLOW, UnitCategory.TOTAL_VOLUME, UnitCategory.PRESSURE, UnitCategory.TEMPERATURE, UnitCategory.TIME_INTERVAL}),
    Unit.UNKNOWN: frozenset({UnitCategory.STD_NORM_FLOW, UnitCategory.TOTAL_STD_NORM_VOLUME, UnitCategory.VOLUMETRIC_FLOW, UnitCategory.TOTAL_VOLUME, UnitCategory.PRESSURE, UnitCategory.TEMPERATURE, UnitCategory.TIME_INTERVAL}),
    Unit.COUNT: frozenset({UnitCategory.STD_NORM_FLOW, UnitCategory.VOLUMETRIC_FLOW, UnitCategory.PRESSURE}),
    Unit.PERCENT: frozenset({UnitCategory.STD_NORM_FLOW, UnitCategory.VOLUMETRIC_FLOW, UnitCategory.PRESSURE}),
    Unit.SUL_M: frozenset({UnitCategory.STD_NORM_FLOW}),
    Unit.SML_S: frozenset({UnitCategory.STD_NORM_FLOW}),
    Unit.SML_M: frozenset({UnitCategory.STD_NORM_FLOW}),
    Unit.SML_H: frozenset({UnitCategory.STD_NORM_FLOW}),
    Unit.SL_S: frozenset({UnitCategory.STD_NORM_FLOW}),
    Unit.SLPM: frozenset({UnitCategory.STD_NORM_FLOW}),
    Unit.SL_H: frozenset({UnitCategory.STD_NORM_FLOW}),
    Unit.SCCS: frozenset({UnitCategory.STD_NORM_FLOW}),
    Unit.SCCM: frozenset({UnitCategory.STD_NORM_FLOW}),
    Unit.SCM3_H: frozenset({UnitCategory.STD_NORM_FLOW}),
    Unit.SM3_M: frozenset({UnitCategory.STD_NORM_FLOW}),
    Unit.SM3_H: frozenset({UnitCategory.STD_NORM_FLOW}),
    Unit.SM3_D: frozenset({UnitCategory.STD_NORM_FLOW}),
    Unit.SIN3_M: frozenset({UnitCategory.STD_NORM_FLOW}),
    Unit.SCFM: frozenset({UnitCategory.STD_NORM_FLOW}),
    Unit.SCFH: frozenset({UnitCategory.STD_NORM_FLOW}),
    Unit.KSCFM: frozenset({UnitCategory.STD_NORM_FLOW}),
    Unit.SCFD: frozenset({UnitCategory.STD_NORM_FLOW}),
    Unit.NUL_M: frozenset({UnitCategory.STD_NORM_FLOW}),
    Unit.NML_S: frozenset({UnitCategory.STD_NORM_FLOW}),
    Unit.NML_M: frozenset({UnitCategory.STD_NORM_FLOW}),
    Unit.NML_H: frozenset({UnitCategory.STD_NORM_FLOW}),
    Unit.NL_S: frozenset({UnitCategory.STD_NORM_FLOW}),
    Unit.NLPM: frozenset({UnitCategory.STD_NORM_FLOW}),
    Unit.NL_H: frozenset({UnitCategory.STD_NORM_FLOW}),
    Unit.NCCS: frozenset({UnitCategory.STD_NORM_FLOW}),
    Unit.NCCM: frozenset({UnitCategory.STD_NORM_FLOW}),
    Unit.NCM3_H: frozenset({UnitCategory.STD_NORM_FLOW}),
    Unit.NM3_M: frozenset({UnitCategory.STD_NORM_FLOW}),
    Unit.NM3_H: frozenset({UnitCategory.STD_NORM_FLOW}),
    Unit.NM3_D: frozenset({UnitCategory.STD_NORM_FLOW}),
    Unit.MG_S: frozenset({UnitCategory.TRUE_MASS_FLOW}),
    Unit.MG_M: frozenset({UnitCategory.TRUE_MASS_FLOW}),
    Unit.G_S: frozenset({UnitCategory.TRUE_MASS_FLOW}),
    Unit.G_M: frozenset({UnitCategory.TRUE_MASS_FLOW}),
    Unit.G_H: frozenset({UnitCategory.TRUE_MASS_FLOW}),
    Unit.KG_M: frozenset({UnitCategory.TRUE_MASS_FLOW}),
    Unit.KG_H: frozenset({UnitCategory.TRUE_MASS_FLOW}),
    Unit.OZ_S: frozenset({UnitCategory.TRUE_MASS_FLOW}),
    Unit.OZ_M: frozenset({UnitCategory.TRUE_MASS_FLOW}),
    Unit.LB_M: frozenset({UnitCategory.TRUE_MASS_FLOW}),
    Unit.LB_H: frozenset({UnitCategory.TRUE_MASS_FLOW}),
    Unit.SUL: frozenset({UnitCategory.TOTAL_STD_NORM_VOLUME}),
    Unit.SML: frozenset({UnitCategory.TOTAL_STD_NORM_VOLUME}),
    Unit.SL: frozenset({UnitCategory.TOTAL_STD_NORM_VOLUME}),
    Unit.SCM3: frozenset({UnitCategory.TOTAL_STD_NORM_VOLUME}),
    Unit.SM3: frozenset({UnitCategory.TOTAL_STD_NORM_VOLUME}),
    Unit.SIN3: frozenset({UnitCategory.TOTAL_STD_NORM_VOLUME}),
    Unit.SFT3: frozenset({UnitCategory.TOTAL_STD_NORM_VOLUME}),
    Unit.KSFT3: frozenset({UnitCategory.TOTAL_STD_NORM_VOLUME}),
    Unit.NUL: frozenset({UnitCategory.TOTAL_STD_NORM_VOLUME}),
    Unit.NML: frozenset({UnitCategory.TOTAL_STD_NORM_VOLUME}),
    Unit.NL: frozenset({UnitCategory.TOTAL_STD_NORM_VOLUME}),
    Unit.NCM3: frozenset({UnitCategory.TOTAL_STD_NORM_VOLUME}),
    Unit.NM3: frozenset({UnitCategory.TOTAL_STD_NORM_VOLUME}),
    Unit.UL_M: frozenset({UnitCategory.VOLUMETRIC_FLOW}),
    Unit.ML_S: frozenset({UnitCategory.VOLUMETRIC_FLOW}),
    Unit.ML_M: frozenset({UnitCategory.VOLUMETRIC_FLOW}),
    Unit.ML_H: frozenset({UnitCategory.VOLUMETRIC_FLOW}),
    Unit.L_S: frozenset({UnitCategory.VOLUMETRIC_FLOW}),
    Unit.LPM: frozenset({UnitCategory.VOLUMETRIC_FLOW}),
    Unit.L_H: frozenset({UnitCategory.VOLUMETRIC_FLOW}),
    Unit.US_GPM: frozenset({UnitCategory.VOLUMETRIC_FLOW}),
    Unit.US_GPH: frozenset({UnitCategory.VOLUMETRIC_FLOW}),
    Unit.CCS: frozenset({UnitCategory.VOLUMETRIC_FLOW}),
    Unit.CCM: frozenset({UnitCategory.VOLUMETRIC_FLOW}),
    Unit.CM3_H: frozenset({UnitCategory.VOLUMETRIC_FLOW}),
    Unit.M3_M: frozenset({UnitCategory.VOLUMETRIC_FLOW}),
    Unit.M3_H: frozenset({UnitCategory.VOLUMETRIC_FLOW}),
    Unit.M3_D: frozenset({UnitCategory.VOLUMETRIC_FLOW}),
    Unit.IN3_M: frozenset({UnitCategory.VOLUMETRIC_FLOW}),
    Unit.CFM: frozenset({UnitCategory.VOLUMETRIC_FLOW}),
    Unit.CFH: frozenset({UnitCategory.VOLUMETRIC_FLOW}),
    Unit.CFD: frozenset({UnitCategory.VOLUMETRIC_FLOW}),
    Unit.UL: frozenset({UnitCategory.TOTAL_VOLUME}),
    Unit.ML: frozenset({UnitCategory.TOTAL_VOLUME}),
    Unit.L: frozenset({UnitCategory.TOTAL_VOLUME}),
    Unit.US_GAL: frozenset({UnitCategory.TOTAL_VOLUME}),
    Unit.CM3: frozenset({UnitCategory.TOTAL_VOLUME}),
    Unit.M3: frozenset({UnitCategory.TOTAL_VOLUME}),
    Unit.IN3: frozenset({UnitCategory.TOTAL_VOLUME}),
    Unit.FT3: frozenset({UnitCategory.TOTAL_VOLUME}),
    Unit.UP: frozenset({UnitCategory.TOTAL_VOLUME}),
    Unit.PA: frozenset({UnitCategory.PRESSURE}),
    Unit.HPA: frozenset({UnitCategory.PRESSURE}),
    Unit.KPA: frozenset({UnitCategory.PRESSURE}),
    Unit.MPA: frozenset({UnitCategory.PRESSURE}),
    Unit.MBAR: frozenset({UnitCategory.PRESSURE}),
    Unit.BAR: frozenset({UnitCategory.PRESSURE}),
    Unit.G_CM2: frozenset({UnitCategory.PRESSURE}),
    Unit.KG_CM2: frozenset({UnitCategory.PRESSURE}),
    Unit.PSI: frozenset({UnitCategory.PRESSURE}),
    Unit.PSF: frozenset({UnitCategory.PRESSURE}),
    Unit.MTORR: frozenset({UnitCategory.PRESSURE}),
    Unit.TORR: frozenset({UnitCategory.PRESSURE}),
    Unit.MMHG: frozenset({UnitCategory.PRESSURE}),
    Unit.INHG: frozenset({UnitCategory.PRESSURE}),
    Unit.MMH2O: frozenset({UnitCategory.PRESSURE}),
    Unit.MMH2O_60F: frozenset({UnitCategory.PRESSURE}),
    Unit.CMH2O: frozenset({UnitCategory.PRESSURE}),
    Unit.CMH2O_60F: frozenset({UnitCategory.PRESSURE}),
    Unit.INH2O: frozenset({UnitCategory.PRESSURE}),
    Unit.INH2O_60F: frozenset({UnitCategory.PRESSURE}),
    Unit.ATM: frozenset({UnitCategory.PRESSURE}),
    Unit.V: frozenset({UnitCategory.PRESSURE}),
    Unit.DEG_C: frozenset({UnitCategory.TEMPERATURE}),
    Unit.DEG_F: frozenset({UnitCategory.TEMPERATURE}),
    Unit.DEG_K: frozenset({UnitCategory.TEMPERATURE}),
    Unit.DEG_RA: frozenset({UnitCategory.TEMPERATURE}),
    Unit.H_M_S: frozenset({UnitCategory.TIME_INTERVAL}),
    Unit.MS: frozenset({UnitCategory.TIME_INTERVAL}),
    Unit.S: frozenset({UnitCategory.TIME_INTERVAL}),
    Unit.M: frozenset({UnitCategory.TIME_INTERVAL}),
    Unit.HOUR: frozenset({UnitCategory.TIME_INTERVAL}),
    Unit.DAY: frozenset({UnitCategory.TIME_INTERVAL}),
}


UNIT_BY_CATEGORY_CODE: Final[Mapping[tuple[UnitCategory, int], Unit]] = {
    (UnitCategory.STD_NORM_FLOW, 0): Unit.DEFAULT,
    (UnitCategory.STD_NORM_FLOW, 1): Unit.UNKNOWN,
    (UnitCategory.STD_NORM_FLOW, 62): Unit.COUNT,
    (UnitCategory.STD_NORM_FLOW, 63): Unit.PERCENT,
    (UnitCategory.STD_NORM_FLOW, 2): Unit.SUL_M,
    (UnitCategory.STD_NORM_FLOW, 3): Unit.SML_S,
    (UnitCategory.STD_NORM_FLOW, 4): Unit.SML_M,
    (UnitCategory.STD_NORM_FLOW, 5): Unit.SML_H,
    (UnitCategory.STD_NORM_FLOW, 6): Unit.SL_S,
    (UnitCategory.STD_NORM_FLOW, 7): Unit.SLPM,
    (UnitCategory.STD_NORM_FLOW, 8): Unit.SL_H,
    (UnitCategory.STD_NORM_FLOW, 11): Unit.SCCS,
    (UnitCategory.STD_NORM_FLOW, 12): Unit.SCCM,
    (UnitCategory.STD_NORM_FLOW, 13): Unit.SCM3_H,
    (UnitCategory.STD_NORM_FLOW, 14): Unit.SM3_M,
    (UnitCategory.STD_NORM_FLOW, 15): Unit.SM3_H,
    (UnitCategory.STD_NORM_FLOW, 16): Unit.SM3_D,
    (UnitCategory.STD_NORM_FLOW, 17): Unit.SIN3_M,
    (UnitCategory.STD_NORM_FLOW, 18): Unit.SCFM,
    (UnitCategory.STD_NORM_FLOW, 19): Unit.SCFH,
    (UnitCategory.STD_NORM_FLOW, 20): Unit.KSCFM,
    (UnitCategory.STD_NORM_FLOW, 21): Unit.SCFD,
    (UnitCategory.STD_NORM_FLOW, 32): Unit.NUL_M,
    (UnitCategory.STD_NORM_FLOW, 33): Unit.NML_S,
    (UnitCategory.STD_NORM_FLOW, 34): Unit.NML_M,
    (UnitCategory.STD_NORM_FLOW, 35): Unit.NML_H,
    (UnitCategory.STD_NORM_FLOW, 36): Unit.NL_S,
    (UnitCategory.STD_NORM_FLOW, 37): Unit.NLPM,
    (UnitCategory.STD_NORM_FLOW, 38): Unit.NL_H,
    (UnitCategory.STD_NORM_FLOW, 41): Unit.NCCS,
    (UnitCategory.STD_NORM_FLOW, 42): Unit.NCCM,
    (UnitCategory.STD_NORM_FLOW, 43): Unit.NCM3_H,
    (UnitCategory.STD_NORM_FLOW, 44): Unit.NM3_M,
    (UnitCategory.STD_NORM_FLOW, 45): Unit.NM3_H,
    (UnitCategory.STD_NORM_FLOW, 46): Unit.NM3_D,
    (UnitCategory.TOTAL_STD_NORM_VOLUME, 0): Unit.DEFAULT,
    (UnitCategory.TOTAL_STD_NORM_VOLUME, 1): Unit.UNKNOWN,
    (UnitCategory.TOTAL_STD_NORM_VOLUME, 2): Unit.SUL,
    (UnitCategory.TOTAL_STD_NORM_VOLUME, 3): Unit.SML,
    (UnitCategory.TOTAL_STD_NORM_VOLUME, 4): Unit.SL,
    (UnitCategory.TOTAL_STD_NORM_VOLUME, 6): Unit.SCM3,
    (UnitCategory.TOTAL_STD_NORM_VOLUME, 7): Unit.SM3,
    (UnitCategory.TOTAL_STD_NORM_VOLUME, 8): Unit.SIN3,
    (UnitCategory.TOTAL_STD_NORM_VOLUME, 9): Unit.SFT3,
    (UnitCategory.TOTAL_STD_NORM_VOLUME, 10): Unit.KSFT3,
    (UnitCategory.TOTAL_STD_NORM_VOLUME, 32): Unit.NUL,
    (UnitCategory.TOTAL_STD_NORM_VOLUME, 33): Unit.NML,
    (UnitCategory.TOTAL_STD_NORM_VOLUME, 34): Unit.NL,
    (UnitCategory.TOTAL_STD_NORM_VOLUME, 36): Unit.NCM3,
    (UnitCategory.TOTAL_STD_NORM_VOLUME, 37): Unit.NM3,
    (UnitCategory.VOLUMETRIC_FLOW, 0): Unit.DEFAULT,
    (UnitCategory.VOLUMETRIC_FLOW, 1): Unit.UNKNOWN,
    (UnitCategory.VOLUMETRIC_FLOW, 62): Unit.COUNT,
    (UnitCategory.VOLUMETRIC_FLOW, 63): Unit.PERCENT,
    (UnitCategory.VOLUMETRIC_FLOW, 2): Unit.UL_M,
    (UnitCategory.VOLUMETRIC_FLOW, 3): Unit.ML_S,
    (UnitCategory.VOLUMETRIC_FLOW, 4): Unit.ML_M,
    (UnitCategory.VOLUMETRIC_FLOW, 5): Unit.ML_H,
    (UnitCategory.VOLUMETRIC_FLOW, 6): Unit.L_S,
    (UnitCategory.VOLUMETRIC_FLOW, 7): Unit.LPM,
    (UnitCategory.VOLUMETRIC_FLOW, 8): Unit.L_H,
    (UnitCategory.VOLUMETRIC_FLOW, 9): Unit.US_GPM,
    (UnitCategory.VOLUMETRIC_FLOW, 10): Unit.US_GPH,
    (UnitCategory.VOLUMETRIC_FLOW, 11): Unit.CCS,
    (UnitCategory.VOLUMETRIC_FLOW, 12): Unit.CCM,
    (UnitCategory.VOLUMETRIC_FLOW, 13): Unit.CM3_H,
    (UnitCategory.VOLUMETRIC_FLOW, 14): Unit.M3_M,
    (UnitCategory.VOLUMETRIC_FLOW, 15): Unit.M3_H,
    (UnitCategory.VOLUMETRIC_FLOW, 16): Unit.M3_D,
    (UnitCategory.VOLUMETRIC_FLOW, 17): Unit.IN3_M,
    (UnitCategory.VOLUMETRIC_FLOW, 18): Unit.CFM,
    (UnitCategory.VOLUMETRIC_FLOW, 19): Unit.CFH,
    (UnitCategory.VOLUMETRIC_FLOW, 21): Unit.CFD,
    (UnitCategory.TOTAL_VOLUME, 0): Unit.DEFAULT,
    (UnitCategory.TOTAL_VOLUME, 1): Unit.UNKNOWN,
    (UnitCategory.TOTAL_VOLUME, 2): Unit.UL,
    (UnitCategory.TOTAL_VOLUME, 3): Unit.ML,
    (UnitCategory.TOTAL_VOLUME, 4): Unit.L,
    (UnitCategory.TOTAL_VOLUME, 5): Unit.US_GAL,
    (UnitCategory.TOTAL_VOLUME, 6): Unit.CM3,
    (UnitCategory.TOTAL_VOLUME, 7): Unit.M3,
    (UnitCategory.TOTAL_VOLUME, 8): Unit.IN3,
    (UnitCategory.TOTAL_VOLUME, 9): Unit.FT3,
    (UnitCategory.TOTAL_VOLUME, 61): Unit.UP,
    (UnitCategory.PRESSURE, 0): Unit.DEFAULT,
    (UnitCategory.PRESSURE, 1): Unit.UNKNOWN,
    (UnitCategory.PRESSURE, 62): Unit.COUNT,
    (UnitCategory.PRESSURE, 63): Unit.PERCENT,
    (UnitCategory.PRESSURE, 2): Unit.PA,
    (UnitCategory.PRESSURE, 3): Unit.HPA,
    (UnitCategory.PRESSURE, 4): Unit.KPA,
    (UnitCategory.PRESSURE, 5): Unit.MPA,
    (UnitCategory.PRESSURE, 6): Unit.MBAR,
    (UnitCategory.PRESSURE, 7): Unit.BAR,
    (UnitCategory.PRESSURE, 8): Unit.G_CM2,
    (UnitCategory.PRESSURE, 9): Unit.KG_CM2,
    (UnitCategory.PRESSURE, 10): Unit.PSI,
    (UnitCategory.PRESSURE, 11): Unit.PSF,
    (UnitCategory.PRESSURE, 12): Unit.MTORR,
    (UnitCategory.PRESSURE, 13): Unit.TORR,
    (UnitCategory.PRESSURE, 14): Unit.MMHG,
    (UnitCategory.PRESSURE, 15): Unit.INHG,
    (UnitCategory.PRESSURE, 16): Unit.MMH2O,
    (UnitCategory.PRESSURE, 17): Unit.MMH2O_60F,
    (UnitCategory.PRESSURE, 18): Unit.CMH2O,
    (UnitCategory.PRESSURE, 19): Unit.CMH2O_60F,
    (UnitCategory.PRESSURE, 20): Unit.INH2O,
    (UnitCategory.PRESSURE, 21): Unit.INH2O_60F,
    (UnitCategory.PRESSURE, 22): Unit.ATM,
    (UnitCategory.PRESSURE, 61): Unit.V,
    (UnitCategory.TEMPERATURE, 0): Unit.DEFAULT,
    (UnitCategory.TEMPERATURE, 1): Unit.UNKNOWN,
    (UnitCategory.TEMPERATURE, 2): Unit.DEG_C,
    (UnitCategory.TEMPERATURE, 3): Unit.DEG_F,
    (UnitCategory.TEMPERATURE, 4): Unit.DEG_K,
    (UnitCategory.TEMPERATURE, 5): Unit.DEG_RA,
    (UnitCategory.TIME_INTERVAL, 0): Unit.DEFAULT,
    (UnitCategory.TIME_INTERVAL, 1): Unit.UNKNOWN,
    (UnitCategory.TIME_INTERVAL, 2): Unit.H_M_S,
    (UnitCategory.TIME_INTERVAL, 3): Unit.MS,
    (UnitCategory.TIME_INTERVAL, 4): Unit.S,
    (UnitCategory.TIME_INTERVAL, 5): Unit.M,
    (UnitCategory.TIME_INTERVAL, 6): Unit.HOUR,
    (UnitCategory.TIME_INTERVAL, 7): Unit.DAY,
    (UnitCategory.TRUE_MASS_FLOW, 64): Unit.MG_S,
    (UnitCategory.TRUE_MASS_FLOW, 65): Unit.MG_M,
    (UnitCategory.TRUE_MASS_FLOW, 66): Unit.G_S,
    (UnitCategory.TRUE_MASS_FLOW, 67): Unit.G_M,
    (UnitCategory.TRUE_MASS_FLOW, 68): Unit.G_H,
    (UnitCategory.TRUE_MASS_FLOW, 69): Unit.KG_M,
    (UnitCategory.TRUE_MASS_FLOW, 70): Unit.KG_H,
    (UnitCategory.TRUE_MASS_FLOW, 71): Unit.OZ_S,
    (UnitCategory.TRUE_MASS_FLOW, 72): Unit.OZ_M,
    (UnitCategory.TRUE_MASS_FLOW, 73): Unit.LB_M,
    (UnitCategory.TRUE_MASS_FLOW, 74): Unit.LB_H,
}
UNIT_ALIASES: Final[Mapping[str, Unit]] = {
    '---': Unit.UNKNOWN,
    'Count': Unit.COUNT,
    'percent': Unit.PERCENT,
    'pct': Unit.PERCENT,
    'SuL/m': Unit.SUL_M,
    'std_microliter_per_min': Unit.SUL_M,
    'std_milliliter_per_sec': Unit.SML_S,
    'std_milliliter_per_min': Unit.SML_M,
    'std_milliliter_per_hour': Unit.SML_H,
    'std_liter_per_sec': Unit.SL_S,
    'std_liter_per_min': Unit.SLPM,
    'SL/m': Unit.SLPM,
    'std_liter_per_hour': Unit.SL_H,
    'std_cubic_cm_per_sec': Unit.SCCS,
    'std_cubic_cm_per_min': Unit.SCCM,
    'Scm3/h': Unit.SCM3_H,
    'std_cubic_cm_per_hour': Unit.SCM3_H,
    'Sm3/m': Unit.SM3_M,
    'std_cubic_meter_per_min': Unit.SM3_M,
    'Sm3/h': Unit.SM3_H,
    'std_cubic_meter_per_hour': Unit.SM3_H,
    'Sm3/d': Unit.SM3_D,
    'std_cubic_meter_per_day': Unit.SM3_D,
    'Sin3/m': Unit.SIN3_M,
    'std_cubic_inch_per_min': Unit.SIN3_M,
    'std_cubic_foot_per_min': Unit.SCFM,
    'std_cubic_foot_per_hour': Unit.SCFH,
    '1000_std_cubic_foot_per_min': Unit.KSCFM,
    'std_cubic_foot_per_day': Unit.SCFD,
    'NuL/m': Unit.NUL_M,
    'norm_microliter_per_min': Unit.NUL_M,
    'norm_milliliter_per_sec': Unit.NML_S,
    'norm_milliliter_per_min': Unit.NML_M,
    'norm_milliliter_per_hour': Unit.NML_H,
    'norm_liter_per_sec': Unit.NL_S,
    'norm_liter_per_min': Unit.NLPM,
    'NL/m': Unit.NLPM,
    'norm_liter_per_hour': Unit.NL_H,
    'norm_cubic_cm_per_sec': Unit.NCCS,
    'norm_cubic_cm_per_min': Unit.NCCM,
    'Ncm3/h': Unit.NCM3_H,
    'norm_cubic_cm_per_hour': Unit.NCM3_H,
    'Nm3/m': Unit.NM3_M,
    'norm_cubic_meter_per_min': Unit.NM3_M,
    'Nm3/h': Unit.NM3_H,
    'norm_cubic_meter_per_hour': Unit.NM3_H,
    'Nm3/d': Unit.NM3_D,
    'norm_cubic_meter_per_day': Unit.NM3_D,
    'milligram_per_sec': Unit.MG_S,
    'milligram_per_min': Unit.MG_M,
    'gram_per_sec': Unit.G_S,
    'gram_per_min': Unit.G_M,
    'gram_per_hour': Unit.G_H,
    'kilogram_per_min': Unit.KG_M,
    'kilogram_per_hour': Unit.KG_H,
    'ounce_per_sec': Unit.OZ_S,
    'ounce_per_min': Unit.OZ_M,
    'pound_per_min': Unit.LB_M,
    'pound_per_hour': Unit.LB_H,
    'SuL': Unit.SUL,
    'std_microliter': Unit.SUL,
    'std_milliliter': Unit.SML,
    'std_liter': Unit.SL,
    'Scm3': Unit.SCM3,
    'std_cubic_cm': Unit.SCM3,
    'Sm3': Unit.SM3,
    'std_cubic_meter': Unit.SM3,
    'Sin3': Unit.SIN3,
    'std_cubic_inch': Unit.SIN3,
    'Sft3': Unit.SFT3,
    'std_cubic_foot': Unit.SFT3,
    'kSft3': Unit.KSFT3,
    'std_1000_cubic_foot': Unit.KSFT3,
    'NuL': Unit.NUL,
    'normal_microliter': Unit.NUL,
    'normal_milliliter': Unit.NML,
    'normal_liter': Unit.NL,
    'Ncm3': Unit.NCM3,
    'normal_cubic_cm': Unit.NCM3,
    'Nm3': Unit.NM3,
    'normal_cubic_meter': Unit.NM3,
    'uL/m': Unit.UL_M,
    'microliter_per_min': Unit.UL_M,
    'milliliter_per_sec': Unit.ML_S,
    'milliliter_per_min': Unit.ML_M,
    'milliliter_per_hour': Unit.ML_H,
    'liter_per_sec': Unit.L_S,
    'liter_per_min': Unit.LPM,
    'L/m': Unit.LPM,
    'liter_per_hour': Unit.L_H,
    'GPM': Unit.US_GPM,
    'gallon_per_min': Unit.US_GPM,
    'GPH': Unit.US_GPH,
    'gallon_per_hour': Unit.US_GPH,
    'cubic_cm_per_sec': Unit.CCS,
    'cubic_cm_per_min': Unit.CCM,
    'cm3/h': Unit.CM3_H,
    'cubic_cm_per_hour': Unit.CM3_H,
    'm3/m': Unit.M3_M,
    'cubic_meter_per_min': Unit.M3_M,
    'm3/h': Unit.M3_H,
    'cubic_meter_per_hour': Unit.M3_H,
    'm3/d': Unit.M3_D,
    'cubic_meter_per_day': Unit.M3_D,
    'in3/m': Unit.IN3_M,
    'cubic_inch_per_min': Unit.IN3_M,
    'cubic_foot_per_min': Unit.CFM,
    'cubic_foot_per_hour': Unit.CFH,
    'cubic_foot_per_day': Unit.CFD,
    'uL': Unit.UL,
    'microliter': Unit.UL,
    'milliliter': Unit.ML,
    'liter': Unit.L,
    'GAL': Unit.US_GAL,
    'gallon': Unit.US_GAL,
    'cm3': Unit.CM3,
    'cubic_cm': Unit.CM3,
    'm3': Unit.M3,
    'cubic_meter': Unit.M3,
    'in3': Unit.IN3,
    'cubic_inch': Unit.IN3,
    'ft3': Unit.FT3,
    'cubic_foot': Unit.FT3,
    'uP': Unit.UP,
    'micropoise': Unit.UP,
    'pascal': Unit.PA,
    'hectopascal': Unit.HPA,
    'kilopascal': Unit.KPA,
    'megapascal': Unit.MPA,
    'millibar': Unit.MBAR,
    'g/cm2': Unit.G_CM2,
    'gram_per_square_cm': Unit.G_CM2,
    'kg/cm2': Unit.KG_CM2,
    'kg/cm': Unit.KG_CM2,
    'kilogram_per_square_cm': Unit.KG_CM2,
    'pound_per_square_inch': Unit.PSI,
    'PSIA': Unit.PSI,
    'PSIG': Unit.PSI,
    'PSID': Unit.PSI,
    'pound_per_square_foot': Unit.PSF,
    'millitorr': Unit.MTORR,
    'Torr': Unit.TORR,
    'millimeter_of_mercury': Unit.MMHG,
    'inch_of_mercury': Unit.INHG,
    'millimeter_of_water': Unit.MMH2O,
    'mmH₂O': Unit.MMH2O,
    'millimeter_of_water_@_60F': Unit.MMH2O_60F,
    'centimeter_of_water': Unit.CMH2O,
    'cmH₂O': Unit.CMH2O,
    'centimeter_of_water_@_60F': Unit.CMH2O_60F,
    'inch_of_water': Unit.INH2O,
    'inH₂O': Unit.INH2O,
    'inch_of_water_@_60F': Unit.INH2O_60F,
    'atmosphere': Unit.ATM,
    'volt': Unit.V,
    'C': Unit.DEG_C,
    'Celsius': Unit.DEG_C,
    '`C': Unit.DEG_C,
    'F': Unit.DEG_F,
    'Fahrenheit': Unit.DEG_F,
    '`F': Unit.DEG_F,
    'K': Unit.DEG_K,
    'Kelvin': Unit.DEG_K,
    'Ra': Unit.DEG_RA,
    'Rankine': Unit.DEG_RA,
    'hours:minutes:seconds': Unit.H_M_S,
    'millisecond': Unit.MS,
    'sec': Unit.S,
    'second': Unit.S,
    'min': Unit.M,
    'minute': Unit.M,
    'h': Unit.HOUR,
    'hr': Unit.HOUR,
    'd': Unit.DAY,
}
