"""GENERATED FILE — do not edit by hand.

Regenerated by ``scripts/gen_codes.py`` from
``src/alicatlib/registry/data/codes.json``. CI enforces that this file matches
the committed ``codes.json``.
"""

from __future__ import annotations

# Placeholder — full enum/registry generation lands in M1 (design §5.3).
# Downstream code should import from ``alicatlib.registry`` once M1 completes,
# not from this module directly.

__all__: list[str] = []
