"""Generate ``src/alicatlib/registry/_codes_gen.py`` from ``codes.json``.

Run locally before committing changes to ``codes.json``. CI re-runs this and
fails if the committed output is stale — see ``.github/workflows/ci.yml``.

Full implementation lands in milestone M1 (design doc §5.3). This placeholder
emits a deterministic header so the CI idempotency check has something stable
to diff against while the package is still being scaffolded.
"""

from __future__ import annotations

import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
CODES_JSON = REPO_ROOT / "src" / "alicatlib" / "registry" / "data" / "codes.json"
OUTPUT = REPO_ROOT / "src" / "alicatlib" / "registry" / "_codes_gen.py"

HEADER = '''"""GENERATED FILE — do not edit by hand.

Regenerated by ``scripts/gen_codes.py`` from
``src/alicatlib/registry/data/codes.json``. CI enforces that this file matches
the committed ``codes.json``.
"""

from __future__ import annotations

# Placeholder — full enum/registry generation lands in M1 (design §5.3).
# Downstream code should import from ``alicatlib.registry`` once M1 completes,
# not from this module directly.

__all__: list[str] = []
'''


def main() -> int:
    """Regenerate ``_codes_gen.py``. Returns 0 on success."""
    if not CODES_JSON.exists():
        raise SystemExit(f"codes.json not found at {CODES_JSON}")

    # Parse to fail fast on malformed JSON, even though we don't use it yet.
    json.loads(CODES_JSON.read_text(encoding="utf-8"))

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(HEADER, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
